### ISSUE TITLE
2.2.4: corruption with cryptdisk on top of writeboost

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#111]
I've experienced easily reproducible corruption with encrypted partition on top of dm-writeboost'ed device.

Layout is simple: HDD + SSD combined into dm-writeboost device `lizard_03wb`;
cryptsetup is applied on top of `lizard_03wb`, formatted as `ext4` file system.

This configuration quickly produces inconsistent file system.

Interestingly, dm-writeboost works flawlessly when it is used on top of encrypted bllock device.

Here is a fragment of `lsblk` showing problematic layout:
~~~~
├─sdg1            8:97   1  14.9G  0 part  
│ └─lizard_03wb 253:0    0   1.8T  0 dm    
│   └─lizard_03 253:5    0   1.8T  0 crypt 
~~~~

__/etc/writeboosttab__:

~~~~
lizard_03wb     /dev/disk/by-uuid/d71b03ff-69cb-4be1-a1d9-2b3eaea10778     /dev/disk/by-partuuid/cd684853-fe21-4cc5-8a2e-1ea0df8249bf    writeback_threshold=70,sync_data_interval=3600,read_cache_threshold=2
~~~~

__/etc/crypttab__:

~~~~
# <target name>  <source device>  <key file>  <options>
lizard_03    /dev/mapper/lizard_03wb    none    noearly,nofail,luks
~~~~

__/etc/fstab__:

~~~~
/dev/mapper/lizard_03    /var/lib/lizardfs/03    ext4    noatime,nodiratime   0    2
~~~~

Encrypted disk was prepared with `cryptsetup luksFormat /dev/disk/by-uuid/d71b03ff-69cb-4be1-a1d9-2b3eaea10778` before _writeboosting_ it.

**Comment by akiradeveloper** [comment]
@onlyjob Thanks for reporting. Let me ask you a question, is this reproducible with dm-writeboost before 2.1.x?

**Comment by onlyjob** [comment]
I'm not sure... I've used this configuration long time ago and it was working in some much older versions. However I did not try last several releases of _dm-writeboost_ in such configuration...

**Comment by akiradeveloper** [comment]
@onlyjob OK. I will make a script and find a version where this issue isn't reproducible.

This could be a serious degradation. I will fix this in 2.2.1.

**Comment by akiradeveloper** [comment]
@onlyjob By the way, you set the read-caching enabled. Did you try with read-caching disabled?

**Comment by onlyjob** [comment]
> Did you try with read-caching disabled?

I _think_ I did and as far as I remember disabling it did not help.
I can tell for sure that with read caching it works when I use cryptdisk under dm-writeboost.
I've used the same (working) configuration to reproduce the problem.

**Comment by akiradeveloper** [comment]
@onlyjob Please tell me the size of backing device and cache device? the backing device seems to be 1.8TB but I see no clue how big the cache device is.

**Comment by onlyjob** [comment]
Caching device is 14.9G, as mention in my first message...

**Comment by akiradeveloper** [comment]
@onlyjob Thanks. I couldn't tell the sdg1 is the caching device.

**Comment by akiradeveloper** [comment]
I wrote this test in the new writeboost-test-suite (https://github.com/akiradeveloper/writeboost-test-suite) but still it's not reproducible. What is the key to reproduce?

```scala
class REPRO_111 extends DMTestSuite {
  test("luks on top of writeboost") {
    slowDevice(Sector.G(12)) { backing =>
      fastDevice(Sector.M(32)) { caching =>
        Writeboost.sweepCaches(caching)
        val options = Map(
          "writeback_threshold" -> 70,
          "sync_data_interval" -> 3600,
          "read_cache_threshold" -> 2
        )
        Writeboost.Table(backing, caching, options).create { wb =>
          Luks(wb) { s =>
            EXT4.format(s)
            EXT4.Mount(s) { mp =>
              Shell.at(mp)(s"stress -v --timeout 30 --hdd 4 --hdd-bytes 512M")
            }
          }
        }
      }
    }
  }
}
```

**Comment by onlyjob** [comment]
I'm not familiar with your test suite. I have 2TB HDD, LUKS encrypted and formatted as _ext4_.
Writeboost applied on top of unencrypted `/dev/mapper` device works but SSD caches unencrypted data. When I re-configured dm-writeboost to cache encrypted HDD and decrypt writeboosted device I could mount file system and browse directories. However shortly after some data was written _ext4_ switched to read-only mode due to file system corruption. I clearly reproduced this problem several times using 4 different hard disks.
I think corruption happens only when file system is modified. Not sure if I can provide further details...

**Comment by akiradeveloper** [comment]
@onlyjob 

> When I re-configured

Please tell me more about this. I can't catch what you did actually.

The test suite says

1. make a 12G HDD called `backing`
2. make a 32M SSD called `caching`
3. sweep the first sector of `caching`
4. make a writeboost'd device called `wb`
5. make a LUKS device on top of `wb` called `s`
6. format the `s` by mkfs.ext4 and mount it, run `stress` on it.

is this what you did? (please ignore the device size) I could't understand what "re-configure" means.

**Is there any possibility that encrypted and non-encrypted data are mixed in either HDD or SSD?** In that case obviously, the filesystem corrupts.

I think we can write a test case as reproducer because the case is reproduced several time and the operations sounds simple.

**Comment by onlyjob** [comment]
Hi Akira,

Thank you for investigating the problem. Much appreciated.

I'm pretty sure I wiped caching device properly but I'll try to reproduce again in hope to find reproducer or reveal a mistake of mine. ;)

**Comment by akiradeveloper** [comment]
@onlyjob I want to release the next 2.2.1 with other fixes and enhancements soon. So for now I will drop this issue from 2.2.1. 

Now that dm-writeboost isn't allowed any regression and that's why I am developing new dedicated test suite for dm-writeboost from scratch. The quality of the test codes is the lifeline.

If this issue is reproduced, the test code should be ported into the test suite too. The best thing is you write the test code but because the test suite is written in Scala, a bit minor language, I will do that work if you provide me the full detail of the reproducer. Please feel free to report a new reproducer when you find one.

Thanks for your efforts on revealing bugs in the module and pushing it to the distributions.

**Comment by onlyjob** [comment]
Fair enough, thanks. Unfortunately problem certainly exists. I've just replaced caching HDD with new (zeroed) one and decided to take an opportunity to reproduce again.
Healthy ext4 file system in encrypted disk exhibited errors in `fsck` when cryptsetup layer initialised on top of writeboosted device:

~~~~
e2fsck 1.42.12 (29-Aug-2014)
lizard_01 contains a file system with errors, check forced.
Resize inode not valid.  Recreate<y>? cancelled!
~~~~

Errors disappeared as soon as I removed writeboost layer.

Size of HDD is 1.8T; size of caching device is 18.6G.

I was wrong in my assumption that writing triggers the problem.
On this instance _fsck.ext4_ revealed the problem before writing...

I still don't know what else can I offer to reproduce. This is on Debian "Jessie" with kernel "Linux debmain 4.6.0-0.bpo.1-amd64 #1 SMP Debian 4.6.1-1~bpo8+1 (2016-06-14) x86_64 GNU/Linux".

Writeboost exhibit no errors when applied on top of cryptdisk device....

**Comment by akiradeveloper** [comment]
@onlyjob can you write a shell script that reproduces the problem? the script should start from zeroing the first sector of the caching device and use dmsetup create and cryptsetup command to set up devices.

**Comment by akiradeveloper** [comment]
Also use smaller disks (HDD should be at most 10GB, SSD should be at most 1GB) so anyone can reproduce easily and analyze quickly. Such a logical error should be reproduced with small disks.

can you see other errors in dmesg in prior to fsck?

I think the start point is reproduce this issue without xxxtab utilities but low-level mkfs and dmsetup and make a reproducer in shell script or Scala.

**Comment by akiradeveloper** [comment]
This is the log of my test program.

```
08:13:04.326 [pool-2-thread-8-ScalaTest-running-REPRO_111] INFO dmtest - [TEST] luks on top of writeboost
08:13:04.367 [pool-2-thread-8-ScalaTest-running-REPRO_111] DEBUG dmtest - reload: table=0 524288 linear /dev/hvg2/back18g  0
08:13:04.502 [pool-2-thread-8-ScalaTest-running-REPRO_111] DEBUG dmtest - reload: table=0 1048576 linear /dev/hvg1/cache2g 0
08:13:04.680 [pool-2-thread-8-ScalaTest-running-REPRO_111] DEBUG dmtest - reload: table=0 524288 writeboost /dev/mapper/dmtest-0 /dev/mapper/dmtest-1 6 writeback_threshold 70 sync_data_interval 3600 read_cache_threshold 2
mke2fs 1.42.5 (29-Jul-2012)
e2fsck 1.42.5 (29-Jul-2012)
[info] REPRO_111:
[info] - luks on top of writeboost
[info] Run completed in 7 seconds, 521 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```

I always do fsck after umount. 

```scala
trait MountApply {
  def stack: Stack
  def checkCmd: String
  def option: String
  private def mount: Path = {
    val mp = Paths.get(s"/tmp/${RandName.alloc}")
    Files.deleteIfExists(mp)
    Files.createDirectory(mp)
    Shell(s"mount ${option} ${stack.bdev.path} ${mp}")
    mp
  }
  private def umount(path: Path) = {
    Shell(s"umount ${path}")
    Files.deleteIfExists(path)
    Shell(s"${checkCmd} ${stack.bdev.path}")
  }
  def apply[A](f: Path => A): A = {
    val mp = mount
    try {
      f(mp)
    } finally {
      umount(mp)
    }
  }
}
```
fsck.ext4 has options -fn

```scala
object EXT4 {
  def format(stack: Stack) = Shell(s"mkfs.ext4 ${stack.bdev.path}")
  case class Mount(stack: Stack) extends MountApply {
    override def option: String = ""
    override def checkCmd: String = "fsck.ext4 -fn"
  }
}
```

**Comment by onlyjob** [comment]
I wrote a script but so far failed to reproduce the problem on smaller disk.
During my experiments I confirmed existence of this problem yet again as I could not even unlock another pre-encrypted HDD 1.8T when it is writeboost-ed... (`No key available with this passphrase.`).

I'll re-configure my script to run on 1.8T image and try again...

**Comment by akiradeveloper** [comment]
@onlyjob 

> During my experiments

with the script? or what you have reported before?

I hope that you can reproduce the problem even with 1.8TB disk but with the script, much better with smaller disks.

I think if you share the script with me at this point, I can figure out what the actual operations are and what was my misunderstadings. If the script is still in experimental and you hesitate to open send me by e-mail.

**Comment by onlyjob** [comment]
> By the way, you set the read-caching enabled. Did you try with read-caching disabled?

Problem is not reproducible with `read_cache_threshold=0`.

**Comment by onlyjob** [comment]
> with the script?

No, without the script... :(  But on another machine with another disk...

> I think if you share the script with me at this point

As soon as it will be proven useful to reproduce the problem. :)

**Comment by akiradeveloper** [comment]
@onlyjob 

> Problem is not reproducible with read_cache_threshold=0.

this is wonderful information. So the we can conclude the bug is in read-caching right?

> As soon as it will be proven useful to reproduce the problem. :)

Ok. will wait.

**Comment by onlyjob** [comment]
> So the we can conclude the bug is in read-caching right?

Yes, I think so.

**Comment by onlyjob** [comment]
Reproduced the issue on 2.2.1 by setting `read_cache_threshold=0` and running `fsck.ext4` _twice_.
First time _fsck_ exhibited no errors (because there were no read cache hits yet) but second time it failed...

**Comment by akiradeveloper** [comment]
@onlyjob 

Doing fsck.ext4 on the crypted writeboost'd device didn't exhibit any error. Please send me a reproducer because I couldn't see what exactly you are doing.

```scala
class REPRO_111 extends DMTestSuite {
  // not reproduced yet
  test("luks on top of writeboost") {
    slowDevice(Sector.G(10)) { backing =>
      fastDevice(Sector.G(1)) { caching =>
        Writeboost.sweepCaches(caching)
        val options = Map(
          "writeback_threshold" -> 70,
          "sync_data_interval" -> 3600,
          "read_cache_threshold" -> 2
        )
        Writeboost.Table(backing, caching, options).create { wb =>
          Luks(wb) { s =>
            EXT4.format(s)
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
          }
        }
      }
    }
  }
}
```

**Comment by onlyjob** [comment]
I don't have reproducer I could share, though I can reliably/manually (and very quickly) reproduce on multiple 80% full (encrypted) 2TB HDDs (ext4).

The script that I wrote does not exhibit this error on smaller devices and so far I did not find a way to fill HDD with that much random data yet (let alone problem of time and space required for "full" reproducer).

Problem only manifests with `read_cache_threshold => 2`.
I hope it is not too hard to identify problem in read caching...

**Comment by onlyjob** [comment]
> because I couldn't see what exactly you are doing

I think I am very specific regarding what exactly am I doing... :(
It is difficult to provide any additional details -- I already gave you all I have.
I shall be happy to try if you have something on your mind.

**Comment by akiradeveloper** [comment]
@onlyjob 

> multiple 80% full (encrypted) 2TB HDDs (ext4)

did you encrypt the backing device? 
What is "80% full"? You haven't mentioned about the space usage.

> Problem only manifests with read_cache_threshold => 1.

You always reproduce with read_cache_threshold => 2. I don't have any idea what evidence you are having to say this.

> I already gave you all I have.

Please share the script (if it isn't a 100% reproducer). Or describe what you are doing in itemized manner. The information is too scattered around. Please reorganize them.

> I hope it is not too hard to identify problem in read caching...

If I get a reproducer, I can definitely fix the problem.

**Comment by akiradeveloper** [comment]
```scala
  test("pattern verifier") {
    slowDevice(Sector.M(128)) { backing =>
      fastDevice(Sector.M(16)) { caching =>
        Writeboost.sweepCaches(caching)
        val options = Map(
          "read_cache_threshold" -> 1
        )
        Writeboost.Table(backing, caching, options).create  { wb =>
          Luks(wb) { s =>
            val ps = new RandomPatternVerifier(s, Sector.K(4))
            ps.stamp(5)
            assert(ps.verify())
            assert(ps.verify())
          }
        }
      }
    }
  }
```

I wrote another test but not reproduced. This test writes a random data and reads them out to verify.

**Comment by akiradeveloper** [comment]
I creased the backing device to 1G so 5% is 50MB. no produce

**Comment by onlyjob** [comment]
> did you encrypt the backing device?

Correct.

> What is "80% full"? You haven't mentioned about the space usage.

Why would you assume that I experienced the issue on empty disk?
Problem was first discovered on actively used server.

> >    Problem only manifests with read_cache_threshold => 1.
> You always reproduce with read_cache_threshold => 2. I don't have any idea what evidence you are having to say this.

You are right, this is just a generalisation on my side. However problem appears to affect my systems only when read cache is populated hence it is not unreasonable to assume that particular value of `read_cache_threshold` is not important. Yet no evidence...

> Please share the script (if it isn't a 100% reproducer).

What's the point of sharing the script if it does not reproduce the problem? Whay are you keep asking for it? I'm still working on it and it is not yet useful to reproduce the problem.

>  Or describe what you are doing in itemized manner.
> The information is too scattered around. Please reorganize them.

I really don't understand what do you want and that makes it hard to comply.

Once again:

I have 2 TB HDD, encrypted with `cryptsetup luksFormat`, with ~80% full _ext4_. (There are 1_000_000+ files in 256 directories).

HDD works perfectly without exhibiting any problems and caching SSD is healthy. Everything is OK when HDD is de-crypted directly but if dm-writeboosted device is constructed and de-crypted with `cryptsetup` (or `cryptdisks_start` and `/etc/crypttab`) then either disk fails to unlock or file system on disk is unusable due to errors. I can reproduce on live system (but not with artificial test) 10 times out of 10 with `read_cache_threshold=2` but not with `read_cache_threshold=0`.

> If I get a reproducer, I can definitely fix the problem.

I recognise the challenge... :)

> I creased the backing device to 1G so 5% is 50MB. no produce

Thank you for trying. Same here, no reproducer on small loop devices... :(

**Comment by akiradeveloper** [comment]
@onlyjob 

> What's the point of sharing the script if it does not reproduce the problem?

Because code is the more precise and quickest way to share information. 

```
# <target name>  <source device>  <key file>  <options>
lizard_03    /dev/mapper/lizard_03wb    none    noearly,nofail,luks
```

You didn't tell me that backing device is encrypted. This is the first time I hear that. I thought you encrypted the WB'd device only.

> and de-crypted with cryptsetup (or cryptdisks_start and /etc/crypttab)

What do you mean by this? You want to say "encrypt"?

Let's reorganize. Is this right?

1. You have a HDD, encrypted
2. Format the HDD with ext4. Making directories, files on it.
3. SSD is healthy (did you do badblock? or just see the SMART?)
4. Construct a WB'd device with the HDD and SSD. Let's call this WB.
5. Encrypt WB by cryptsetup. 
6. fsck.ext4 twice on the WB'd device
7. Then see the error

```
- WB (encrypted)
   - HDD (encrytped. formatted by ext4)
   - SSD
```

**Comment by akiradeveloper** [comment]
I find a code to exhibit error but with read_cache_threshold = 0 (please try to understand what this code says. I bet you are capable of understanding it because you can write shell script fluently)

```scala
  test("encrypted backing") {
    slowDevice(Sector.M(128)) { backing =>
      Luks(backing) { luks =>
        EXT4.format(luks)
        EXT4.Mount(luks) { mp =>
        }
        Shell(s"fsck.ext4 -fn ${luks.bdev.path}")
        fastDevice(Sector.M(16)) { caching =>
          Writeboost.sweepCaches(caching)
          val options = Map(
            "read_cache_threshold" -> 0
          )
          Writeboost.Table(backing, caching, options).create { s =>
            Shell(s"fsck.ext4 -fn ${s.bdev.path}") // ERROR!!
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
          }
        }
      }
    }
  }
```

```
12:16:03.225 [pool-2-thread-8-ScalaTest-running-REPRO_111] ERROR dmtest - sh> [fsck.ext4, -fn, /dev/mapper/dmtest-4] err=12
[info] REPRO_111:
[info] - encrypted backing *** FAILED ***
[info]   scala.MatchError: Left(12) (of class scala.util.Left)
[info]   at dmtest.Shell$.apply(Shell.scala:20)
[info]   at dmtest.writeboost.REPRO_111$$anonfun$3$$anonfun$apply$mcV$sp$3$$anonfun$apply$7$$anonfun$apply$9$$anonfun$apply$10.apply(REPRO_111.scala:61)
```

I guess the reason is: Writeboost splits the IO into 4KB chunks so the dm-crypt can't properly descrypt the data. Because of some alignment issue.

**Comment by onlyjob** [comment]
> You didn't tell me that backing device is encrypted

I did. Multiple times. That was essential part of the report. But never mind, let's assume I was not precise enough... :(


> >  and de-crypted with cryptsetup (or cryptdisks_start and /etc/crypttab)

> What do you mean by this? You want to say "encrypt"?

I fail to recognise what you do not understand. I've written exactly what I meant. Sorry I can't clarify any further... I feel we are walking circles...


>    You have a HDD, encrypted

correct.

>    Format the HDD with ext4. Making directories, files on it.

Well, it already have data but yes, close enough.

>    SSD is healthy (did you do badblock? or just see the SMART?)

Yes full `badblocks -w`. Caching device exhibits no problems.

>    Construct a WB'd device with the HDD and SSD. Let's call this WB.
>    Encrypt WB by cryptsetup.

De-crypt with `cryptsetup open`. HDD is pre-encrypted.
Here is where it fails on one system.

>    fsck.ext4 twice on the WB.
>    Then see the error

Correct. On another system where WB successfully de-crypted first pass of `fsck.ext4` is OK (no errors) but second one produces many fake errors.
No errors on de-crypted HDD (without WB).

**Comment by akiradeveloper** [comment]
> I guess the reason is: Writeboost splits the IO into 4KB chunks so the dm-crypt can't properly descrypt the data. Because of some alignment issue.

Sorry, not sure about this.

**Comment by onlyjob** [comment]
> Because of some alignment issue

Thank you. I suspect alignment issue as well. I just can't reproduce it in artificial test...

**Comment by akiradeveloper** [comment]
@onlyjob 

> De-crypt with cryptsetup open. HDD is pre-encrypted.
Here is where it fails on one system.

Again, I guess what you did is:

1. cryptsetup luksFormat HDD 
2. cryptsetup luksOpen HDD -> A
3. format A with ext4
4. make directories on A
5. cryptsetup luksClose A
6. construct a WB'd device with the HDD + SSD. let's call this B
7. cryptsetup luksOpen B -> C
8. fsck.ext4 C

**Comment by akiradeveloper** [comment]
oh no... I found a mistake in the test code

**Comment by akiradeveloper** [comment]
Sorry, this doesn't reproduce the problem.

```scala
  test("encrypted backing") {
    slowDevice(Sector.M(128)) { backing =>
      Luks(backing) { luks =>
        EXT4.format(luks)
        EXT4.Mount(luks) { mp =>
        }
        Shell(s"fsck.ext4 -fn ${luks.bdev.path}")
        fastDevice(Sector.M(16)) { caching =>
          Writeboost.sweepCaches(caching)
          val options = Map(
            "read_cache_threshold" -> 1
          )
          Writeboost.Table(luks, caching, options).create { s =>
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
          }
        }
      }
    }
  }
```

**Comment by onlyjob** [comment]
> Again, I guess what you did is: 1...8

Yes, this is pretty accurate understanding. Thanks. :)

**Comment by akiradeveloper** [comment]
@onlyjob I will try to reproduce this problem continuously. My code is bit different from yours. needs a change to the framework a little bit

**Comment by akiradeveloper** [comment]
@onlyjob 

please be sure

* You use the same key to open B above
* You sweep the first sector of the SSD before constructing B

**Comment by akiradeveloper** [comment]
I will go to the gym! see you later

**Comment by onlyjob** [comment]
> please be sure

Of course. :)

> I will go to the gym! see you later

Thanks for all your time. :)

**Comment by akiradeveloper** [comment]
@onlyjob 

You shouldn't close A at 5 because luksOpen B doesn't mean to open A

**Comment by akiradeveloper** [comment]
I made a test based on your actual operation sequence. Parameters are arranged so I think they are more useful to reproduce.

But unfortunately even this test doesn't reproduce just makes me more confident of the writeboost's code.

```scala
  test("encrypted backing") {
    slowDevice(Sector.G(1)) { backing =>
      Luks.format(backing)
      Luks(backing) { luks => // open
        EXT4.format(luks)
        EXT4.Mount(luks) { mp =>
          val crf = new CreateRandomFiles(mp)
          crf.numDirectories = 100
          crf.numFiles = 300
          crf.fileSize = 1
          crf.create()
        }
        Shell(s"fsck.ext4 -fn ${luks.bdev.path}")
      } // close
      fastDevice(Sector.G(1)) { caching =>
        Writeboost.sweepCaches(caching)
        val options = Map(
          "read_cache_threshold" -> 127
        )
        Writeboost.Table(backing, caching, options).create { wb =>
          Luks(wb) { s => // open
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
          } // close
        }
      }
    }
  }
```

**Comment by onlyjob** [comment]
>  more confident of the writeboost's code.

I agree that generally dm-writeboost code is good. However we are missing something - a block number overflow or something that causes the issue. It is hard to reproduce but it is real. I'm confident about that and I've been operating dm-writeboost on many disks on several servers ever since its first release.
I'm pretty sure it is not something that I did wrong and even if I did, it would be bug anyway since it should be possible to prevent the issue...

**Comment by akiradeveloper** [comment]
@onlyjob 

To reproduce, you run a fsck twice. Please give me `dmsetup status` at three places.

stat
1st fsck
stat
2nd fsck
stat

The stat is useful to analyze what was happening.

And the type of CPU please

**Comment by akiradeveloper** [comment]
@onlyjob 

Can you reproduce it with read_cache_threshold = 127?
And please find the least set of parameters to writeboost. I think only read_cache_threshold suffices.

**Comment by akiradeveloper** [comment]
@onlyjob 

Instead of luksOpen the writeboost'ed device constructed, what if you luksOpen the encrypted HDD and construct writeboost with SSD?

So, I want to ask you to do:

1. Find the least set of parameters
2. then send me the stats in said three places
3. try open the backing HDD instead of writeboost'ed device

**Comment by onlyjob** [comment]
> 3. try open the backing HDD instead of writeboost'ed device

Since I can't open writeboosted device this is exactly how it works now, without a problem.
I'll gather required information and stat during next maintenance window. 

On both machines where I reproduced the problem the CPU is x86_64: `Intel(R) Core(TM) i7` and `Intel(R) Core(TM) i3-4160`.

**Comment by akiradeveloper** [comment]
@onlyjob Do you think the combination of writeboost (with read-caching enabled) and the LUKS only makes the problem? 

https://www.redhat.com/archives/dm-devel/2016-June/msg00000.html

There is a known issue about the combination of dm-crypt and bcache. I bet this isn't relevant to our problem but dm-crypt sometimes behaves badly in combination with other stack. Before the issue above, many bugs are reported about dm-crypt. In my opinion, this is due to its design failure.

So writeboost and LUKS makes another issue sounds reasonable to me.

If you are confident that the combination with LUKS only makes this happen I will look deeply into the dm-crypt's code and known issues in the ML.

**Comment by akiradeveloper** [comment]
@onlyjob btw, status can become more readable using wb_status in https://github.com/akiradeveloper/dm-writeboost-tools. You can share the raw status line but would be more thankful if you use this.

**Comment by akiradeveloper** [comment]
@onlyjob  

> I've just replaced caching HDD with new (zeroed) one and decided to take an opportunity to reproduce again.

Are you using HDD as the caching device???

**Comment by akiradeveloper** [comment]
@onlyjob  please share the memory usage (%) before constructing wb'd device

**Comment by akiradeveloper** [comment]
@onlyjob how about doing `dmsetup suspend; dmsetup resume` before the second fsck? This operation drops all rambuf data and thus helpful to isolate the problem.

**Comment by akiradeveloper** [comment]
@onlyjob Didn't see no error during the initialization of writeboost'd device? Please see the dmseg

**Comment by akiradeveloper** [comment]
I will close this issue for the moment because the issue isn't updated since 2.2.1. If it reproduces again in the lastest version feel free to reopen the issue.

**Comment by akiradeveloper** [comment]
I am confident that this issue will be resolved as #150 is resolved.

Dmitry said

> I can tell for sure that with read caching it works when I use cryptdisk under dm-writeboost.

> When I re-configured dm-writeboost to cache encrypted HDD and decrypt writeboosted device I could mount file system and browse directories.

this is because wrapping the backing store with some DM target is the key to set bio payload in `clone_endio` as I reported here (https://www.redhat.com/archives/dm-devel/2016-September/msg00043.html). Otherwise the payload is junk and leads to data corruption.

I will reopen this issue because it's still live.

**Comment by akiradeveloper** [comment]
Bit arbitrary though, there is a reproducer.

```scala
  test("luks on top of writeboost") {
    Memory(Sector.M(100)) { backing =>
      Memory(Sector.M(100)) { caching =>
        Writeboost.sweepCaches(caching)
        val options = Map(
          "read_cache_threshold" -> 127,
          "write_around_mode" -> 1,
          "nr_read_cache_cells" -> 8
        )
        Writeboost.Table(backing, caching, options).create { wb =>
          Luks.format(wb)
          Luks(wb) { s =>
            EXT4.format(s)
            wb.status
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
            wb.status
            Shell(s"fsck.ext4 -fn ${s.bdev.path}")
            wb.status
          }
        }
      }
    }
  }
```

```
00:04:07.038 [pool-2-thread-5-ScalaTest-running-REPRO_111] DEBUG dmtest - sh> [fsck.ext4, -fn, /dev/mapper/dmtest-1]
e2fsck 1.42.5 (29-Jul-2012)
fsck.ext4: Illegal inode number while checking ext3 journal for /dev/mapper/dmtest-1
```

**Comment by akiradeveloper** [comment]
the for-benjamin-v5 (fix candidate for #150) fixes this.

**Comment by onlyjob** [comment]
2.2.5 is still affected by this problem. Please re-open.

**Comment by akiradeveloper** [comment]
@onlyjob really...

**Comment by akiradeveloper** [comment]
I thought #150 is quite similar to this. But maybe there is some other bugs in read-caching?

**Comment by onlyjob** [comment]
Thanks... It is easy for me to reproduce on storage node but hard to make an artificial reproducer and gather all detailed information for you... I'm going to make another attempt to write a reproducer script...

**Comment by akiradeveloper** [comment]
@onlyjob What if you wrap the backing store by DM linear? In #150 we learn that using LVM devices we can easy some read-caching problem.

**Comment by akiradeveloper** [comment]
and please share the dmesg

**Comment by onlyjob** [comment]
Akira, I'm sorry! I've just realised that due to embarrassing mistake on my side I was still running 2.2.4 when I re-run my tests. I tested 2.2.5 (twice) and indeed it fixed the problem. Thank you so much for all your hard work.

**Comment by akiradeveloper** [comment]
@onlyjob No problem. I am so relieved to hear that.
