### ISSUE TITLE
read should be failed when merging is needed and reading from caching device failed

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#116]
partial read hit on the caching device results in as follows:

1. read from the backing device (A)
2. read from the caching device (B)
3. overwrite A by B
4. and then ack

the code below acks OK even though the 2 failed.

**2.2.0**
```c
	if (unlikely(dirtiness.data_bits != 255)) {
		int err = fill_payload_by_backing(wb, bio); // A
		if (err)
			goto read_mb_exit;

		if (dirtiness.is_dirty) {
			void *buf = read_mb(wb, res.found_seg, res.found_mb, dirtiness.data_bits); // B
			if (!buf)
				goto read_mb_exit; // FIXME!!! should be err != 0
			copy_to_bio_payload(bio, buf, dirtiness.data_bits); // C
			mempool_free(buf, wb->buf_8_pool);
		}

read_mb_exit:
		dec_inflight_ios(wb, res.found_seg);

		if (unlikely(err))
			bio_io_error(bio);
		else
			bio_endio_compat(bio, 0);

		return DM_MAPIO_SUBMITTED;
	}
```

I think this bug was introduced in 2.2.0 at commit https://github.com/akiradeveloper/dm-writeboost/commit/fabbc10432dbe58d37d58cfa47d54ff8aafde035

because in 2.1.2, when `writeback_wb` failed, bio is flagged with error.

**2.1.2**
```c
		if (dirtiness.is_dirty)
			io_res = writeback_mb(wb, res.found_seg, res.found_mb, dirtiness.data_bits, true);
			if (!io_res)
				if (mark_clean_mb(wb, res.found_mb))
					dec_nr_dirty_caches(wb);
		dec_inflight_ios(wb, res.found_seg);
		bio_remap(bio, wb->backing_dev, bi_sector(bio));
	}

	if (unlikely(io_res)) {
		bio_io_error(bio);
		return DM_MAPIO_SUBMITTED;
	}
```

**Comment by akiradeveloper** [comment]
@onlyjob 

You are now finding the reproducer for #111 and you aren't sure the problem is exhibited with 2.1.2.

If the issue is __not__ reproducible with 2.1.2 then this fix could possibly solve #111. Did you test it with 2.1.2?

**Comment by akiradeveloper** [comment]
I can write a white-box reproducer for this issue if dm-flakey is fixed.

https://www.redhat.com/archives/dm-devel/2016-July/msg00088.html

But unfortunately it's buggy and not fixed soon.

**Comment by onlyjob** [comment]
No I did not test with 2.1.2... I'll test again with 2.2.1, once it is released. Thank you.

**Comment by akiradeveloper** [comment]
I found this is unlikely the case for #111 because this case is only relevant to partial read-hit but #111 is concluded that it's only relevant to read-caching that isn't relevant to partial read-hit.

**Comment by akiradeveloper** [comment]
> But unfortunately it's buggy and not fixed soon.

https://www.redhat.com/archives/dm-devel/2016-July/msg00561.html

With Mike's patch dm-flakey is fixed. Then REPRO_116 shows ok for me.
