### ISSUE TITLE
should use kmap to access bio page

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#125]
The current implementation that directly uses page_address of the bvec page should be replaced with using kmap and kunmap (more precisely kmap_atomic but they are essentially the same)

```c
static void copy_bio_payload(void *buf, struct bio *bio)
{
	bv_vec vec;
	bv_it it;
	bio_for_each_segment(vec, bio, it) {
		size_t l = bv_len(vec);
		memcpy(buf, page_address(bv_page(vec)) + bv_offset(vec), l);
		buf += l;
	}
}
```

This is a code from dm-log-writes that also copies the bvec page into the memory allocate by itself as well. I think writeboost should do this way.

```c
632         bio_for_each_segment(bv, bio, iter) {
633                 struct page *page;
634                 void *src, *dst;
635
636                 page = alloc_page(GFP_NOIO);
637                 if (!page) {
638                         DMERR("Error allocing page");
639                         free_pending_block(lc, block);
640                         spin_lock_irq(&lc->blocks_lock);
641                         lc->logging_enabled = false;
642                         spin_unlock_irq(&lc->blocks_lock);
643                         return -ENOMEM;
644                 }
645
646                 src = kmap_atomic(bv.bv_page);
647                 dst = kmap_atomic(page);
648                 memcpy(dst, src + bv.bv_offset, bv.bv_len);
649                 kunmap_atomic(dst);
650                 kunmap_atomic(src);
651                 block->vecs[i].bv_page = page;
652                 block->vecs[i].bv_len = bv.bv_len;
653                 block->vec_cnt++;
654                 i++;
655         }
```

The reason isn't completely sure for me but we found a description

```
When and where to use kmap_atomic() is straightforward.  It is used when code
wants to access the contents of a page that might be allocated from high memory
(see __GFP_HIGHMEM), for example a page in the pagecache.  
```

in vm/highmem.txt. I believe this means we should do this regardless of 32/64 bit mode.

And I can make this change confidently because it falls back to page_address in case it's not necessary. So it's simply better than using page_address directly, in terms of correctness.

```c
  6 void *kmap(struct page *page)
  7 {
  8         might_sleep();
  9         if (!PageHighMem(page))
 10                 return page_address(page);
 11         return kmap_high(page);
 12 }
 13 EXPORT_SYMBOL(kmap);
```

This fix could be a #111 killer because there is possibility dm-crypt passes such memory region that should be accessed by kmap. But I access the region with page_address that assumes the page is in the lowmem or already kmapped that returns NULL otherwise, consequently I memcpy the address 0 data.

**Comment by akiradeveloper** [comment]
@onlyjob Will you test #111 with this fix? (if you will please use fix-125 branch) Or will you start testing after I release 2.2.2?

Since I believe this is a critical bug fix I will release 2.2.2 soon including some other fixes/improvements but it's better to know if this is really a fix for #111.

**Comment by onlyjob** [comment]
Sorry I did not have a chance to attempt another round of tests yet... Might be able to do it tomorrow but I can't give any guarantees... Eventually I'll test but I'm not sure when... Hopefully soon, if time allows...

**Comment by akiradeveloper** [comment]
@onlyjob no problem. I will make for-dmitry branch today that includes some other fixes then please use it. Don't forget to take the stat before and after the fscks.
