### ISSUE TITLE
rename write_through_mode to write_around_mode

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#130]
I am so sorry guys.

I want to fold another fix into v2.2.2. (or do I release a new version 2.2.3?)

```
write_through_mode (bool)
  accepts: 0..1
  default: 0
By enabling this, dm-writeboost never cache dirty data by writing data directly
to the backing device.
```

this is generally called "write around".

Since there is no user of this mode at the present, I believe I can change without dumping up the major version.

**Comment by akiradeveloper** [comment]
I will release 2.2.3 tomorrow

**Comment by pttpzp** [comment]
@akiradeveloper ,yes ,if nothing was wrote to cache device,"write around" is more precise."write through" is more likely "write back"+"flush to back device immediately".
