### ISSUE TITLE
Issue with dropping and rebuilding cache

### ISSUE THREAD

**Issue by joeey1984ad** [akiradeveloper/dm-writeboost#141]
Hello, I am using the latest version of dm-writeboost V2.2.3. My kernel is Centos 7.2 
3.10.0-327.28.2.el7.x86_64

The cache is in defaullt mode and seems to cache the block device, however when I try to drop the caches or restart and try to rebuild the cache, the process hangs for ever. I only have around 6G used on the device.

This is how I created the block device,

/dev/mdo  raid 1 HDD
/dev/md2  raid 1  SSD
------------------
sudo dmsetup create mylv --table "0 `blockdev --getsize /dev/md0` writeboost /dev/md0  /dev/md2"

 dd if=/dev/zero of=/dev/mapper/mylv oflag=direct bs=512 count=1

mkfs.ext4   /dev/mapper/mylv

mount /dev/mapper/mylv  /home

Please guide me what is happening here. 

Thanks,
Joseph

**Comment by akiradeveloper** [comment]
@joeey1984ad Hi Joseph,

I have several questions to you:

1. why do you `dd mylv` before mkfs? To first install the caching, the document says "zeroing the first one sector of the caching device before making writeboost'ed device". I thought that you misunderstood this.
2. what did you do actually to "drop the caches"? Did you send drop_caches message to writeboost'd device?
3. which process do you mean by "the process"?

**Comment by joeey1984ad** [comment]
Hello, thanks for your reply.

1. I did use 'dd mvlv' before making the device and received the same issue.
2. I used 'dmsetup message mylv 0 drop_caches', after restart I used the same 'dmsetup create' command without 'dd mylv'.
3. by "the process " I mean after hitting 'dmsetup message mylv 0 drop_caches' command, The blink identifier remains hanging even after waiting 20-30 . as mentioned the data is only around 6G.

Here is a snapshot,
![sample](https://cloud.githubusercontent.com/assets/12181529/17724858/79e7bf34-63fa-11e6-8699-d90b5ff0e4bd.jpg)

**Comment by joeey1984ad** [comment]
To clarify, regarding the first issue. If I use 'dd mylv' before making a 'writeboosted device' for '/dev/mapper/mylv' , I get the following error, 
"dd: failed to open ‘/dev/mapper/mylv’: Invalid argument"

Doesn't that mean /dev/mapper/mylv does not exist prior to making the 'writeboosted device' ?

Please guide me.

Thank you

**Comment by akiradeveloper** [comment]
@joeey1984ad 

1. You are doing wrong. What you should do before making the writeboost'd device is zeroing the first sector of "/dev/md2". This discards all cache data in the caching device (md2) and so writeboost driver runs reformatting in initialization (so do this only once at the first installation)
2. I see.
3. So you wrote 6GB of random data into the mylv? Writing back 6GB of data to the backing device (must be HDDs) spends more than 20-30 minutes. 

To know what is happening in more detail, I think you should see the sysstat to see if writeback is really working and how fast is it. Try `sar -d 1`.

**Comment by akiradeveloper** [comment]
@joeey1984ad This is just a tip for the production use regarding the writeback. It's often better to set `writeback_threshold` to 70 or around. You are using writeboost without any tunes so writeback never happens until the caching device becomes full or is urged to do so (by sending drop_caches message as you did)

All additional features including read caching is by default disabled in writeboost for design reason.

**Comment by joeey1984ad** [comment]
Ok, I will make the writeboosted device based on what you said and let you know within a few minutes.

One question though, in the default mode, is write back enabled? because "writeback_threshold=0'. Should I change it to 1 to enable writeback?

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> One question though, in the default mode, is write back enabled? because "writeback_threshold=0'. Should I change it to 1 to enable writeback?

I already answered this question but let's again clarify - Please set it to 70 for now. Then writeboost writebacks data from caching device to the backing device at the same time you write some data to the writeboost'd device.

**Comment by joeey1984ad** [comment]
Ok, I created the block exactly as mentioned. 

1. dd if=/dev/zero of=/dev/mapper/mylv oflag=direct bs=512 count=1
2. dmsetup create mylv --table "0 blockdev --getsize /dev/md0 writeboost /dev/md0 /dev/md2"
3. mkfs.ext4 /dev/mapper/mylv
4 .mount /dev/mapper/mylv /home
5. changed "writeback_threshold=70'
6. created around 6gb MYSQL  DATA on /home
7 .dmsetup message mylv 0 drop_caches

It still hangs!

**Comment by joeey1984ad** [comment]
i am sorry, step one is wrong
1. dd if=/dev/zero of=/dev/md2 oflag=direct bs=512 count=1

**Comment by akiradeveloper** [comment]
@joeey1984ad 

how did you change writeback_threshold=70? Please share the result of `dmsetup status mylv`

And as I advised, please see the sysstat.

**Comment by joeey1984ad** [comment]
1. dmsetup message mylv 2 writeback_threshold 0 
2. 0 3906766976 writeboost 18606009 111085757 874691 146505 146504 16008 7662051 0 170 0 0 1 480 0 0 0 9212053 0 0 0 3201397 0 0 27674 10 writeback_threshold 70 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 1
3. I have the snapshot of "
![sample2](https://cloud.githubusercontent.com/assets/12181529/17725515/d41e7c6c-6400-11e6-8df6-64812545acfe.jpg)
sar -d 1" attached.

**Comment by akiradeveloper** [comment]
@joeey1984ad Please share the result of `lsblk`. I don't know which is md0 or md2

**Comment by akiradeveloper** [comment]
But from the stat only I can see that your caching device have many dirty blocks and writing them back very hard.

**Comment by joeey1984ad** [comment]
As mentioned above. 

md0  is HDD RAID1
md2  is SSD  RAID1

lsblk

![3](https://cloud.githubusercontent.com/assets/12181529/17725601/888d633e-6401-11e6-8b9b-dd877e22b615.jpg)

**Comment by joeey1984ad** [comment]
Hmm. I created 5000000 rows of data, which is around 1 GB. Combined with my log file and everything around 6 GB DATA. Then I did a RW test with sysbench for 20sec. Then used "dmsetup message mylv 0 drop_caches" to drop data to HDD md0.

**Comment by akiradeveloper** [comment]
@joeey1984ad Thanks. I see

md0 is 9:0 and md2 is 9:2

And let's see the 1:27:37 line in the sysstat. I means "writeboost reads 16MB from the md2 and writes them back to md0"

So you are system is NOT hang but it's just writing back all dirty data to the backing store.

**Comment by joeey1984ad** [comment]
Why does it take forever to drop for such small DATA. I waited more than 30 min and still does not finish?

**Comment by akiradeveloper** [comment]
@joeey1984ad FYI, you don't need to always drop all caches before reboot because the data is safely saved in the caching device (they aren't volatile!)

**Comment by joeey1984ad** [comment]
Understood. As mentioned, even after reboot, when I try to recreate writeboost, it hangs forever. I can not re setup after reboot because it takes forever for such small DATA. Is this normal?

**Comment by joeey1984ad** [comment]
I read other issues posted here and people mentioned, the dmsetup after reboot should only take 5-10 min for a relatively large data. Here I only have 6G and it never seems to finish the job.

**Comment by akiradeveloper** [comment]
@joeey1984ad Please always see the sysstat when you are wondering if it hangs.

I think it's normal because writeboost replays all logs in the caching device on the reboot. But I don't think it doesn't problem users so much because rebooting storage server is really an seldom event in the production.

**Comment by akiradeveloper** [comment]
@joeey1984ad The reboot time is proportional to the size of caching device. I think rebooting doesn't take 30mins in your case.

**Comment by joeey1984ad** [comment]
I tried rebuilding after reboot. It took over 30 min, the I cancelled. I still think this is not normal. Imagine for a production server even if the server needs one reboot every 2-3 years for whatever reason, you mean to tell me it will take several hours to recreate writeboost?

**Comment by akiradeveloper** [comment]
@joeey1984ad Please see the sysstat. It's not fair to complain without sharing any evidence that my driver is doing wrong.

> Imagine for a production server even if the server needs one reboot every 2-3 years for whatever reason, you mean to tell me it will take several hours to recreate writeboost?

But I can say yes. It's a scheduled maintenance which should include other works. So taking several hours is even acceptable for many users. This is the nature of log-structured method that we can avoid. log-structured filesystem also have the same property

**Comment by joeey1984ad** [comment]
I think the speed of writeboost is amazing even compared to LVM cache. Since writeboost requires rebuild after every reboot, and taking such long time seems to be a normal operation, then this will be useless for any production environment.

**Comment by joeey1984ad** [comment]
You still have not explained why I am still waiting for over 30min for ONLY 6G of data to be written back to my HDD?

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> I think the speed of writeboost is amazing even compared to LVM cache. 

Yes.

> Since writeboost requires rebuild after every reboot

It doesn't do any rebuilding on reboot. It's just iterating over the caching device to reconstruct the metadata.

**Comment by joeey1984ad** [comment]
when I reboot, and hit the "sudo dmsetup create mylv --table "0 blockdev --getsize /dev/md0 writeboost /dev/md0 /dev/md2" takes FOREVER for 6GB DATA. Please explain why? I am still waiting to recreate my block device after reboot!

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> You still have not explained why I am still waiting for over 30min for ONLY 6G of data to be written back to my HDD?

It's just because your HDD is slow. writeboost can't write the data back to the backing any faster than the backing store's write throughput.

Since HDD's random write throughput is typically few MB/sec. So it's not that amazing to take 30mins or hours to write them back all. This is a simple arithmetic.

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> takes FOREVER

Don't you this word if you are an engineer.

You should make sure what is happening by seeing the sysstat. It should be reading the logs on the caching device.

**Comment by joeey1984ad** [comment]
Writing 6GB to my harddrive takes 5-10 minutes MAX. I have 72000 RPMS SERVER HDD. They are very fast. It does not make sense. I promise you even if I leave the drop cache for a day, it still will not DROP caches. I am ready to prove it to you. I think it really is unprofessional on your part to assume such a thing is OK for production servers or even any servers in that manner.

**Comment by joeey1984ad** [comment]
Let me run this for over a day!? What will you answer be, if the cache is still not created after reboot?

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> I think it really is unprofessional on your part to assume such a thing is OK for production servers or even any servers in that manner.

You are too rude. Please discuss more politely.

It's ok to wait for a day but first prove that your operation is perfect. To prove it, you should first do the same thing with smaller data than 6GB. say 6MB. If it doesn't finish in a minute, your operations is something wrong

**Comment by joeey1984ad** [comment]
I had  high respect for you and really believed this project had high potential.  If you believe this waiting time is OK then you air are fooling yourself. If I am doing something wrong then it should be noted and explained for the sake of other users. No one actually has any minute small data like 6mb. But to prove you wrong I will recreated a 6MB data and test it.

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> If you believe this waiting time is OK then you sir are fooling yourself.

Please realize that your comment is fooling those who believes writeboost is the best even knowing that the reboot time is long.

It's ok to issue some technical problem but just complaining based on his or her own experience is really unwelcome.

**Comment by joeey1984ad** [comment]
@akiradeveloper 
It's ok to wait for a day but first prove that your operation is perfect. To prove it, you should first do the same thing with smaller data than 6GB. say 6MB. If it doesn't finish in a minute, your operations is something wrong.

Based on that suggestion. I have created  ONLY 6MB data on writeboost device. Restarted my server and tried to reccreate writeboost device for ONLY 6MB file. I Am still waiting for the device to be recreated and no luck. Here is "
![4](https://cloud.githubusercontent.com/assets/12181529/17726906/5214c776-640a-11e6-829d-74a69dbfc0c6.jpg)
sar -d 1" results,

**Comment by akiradeveloper** [comment]
@joeey1984ad please show me `dmsetup table` and `dmsetup status mylv`

**Comment by joeey1984ad** [comment]
I have to reformat disks and recreate the writeboost cache again since I am still waiting dmsetup. Give me a few minutes. something definitely is wrong, could it be centos or the kernel ?

**Comment by joeey1984ad** [comment]
1. dmsetup table
mylv: 0 3906766976 writeboost  9:0 9:2

2. dmsetup status mylv
0 3906766976 writeboost 1422227 111085757 874691 11199 11198 7104 515222 0 159 0 0 1 446 0 0 0 1408829 0 0 0 183 0 0 55 10 writeback_threshold 70 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

**Comment by joeey1984ad** [comment]
I put two small files (adding to 6M) in writeboost device then tried to drop them to md0. It seems dropping cache never takes place.

**Comment by akiradeveloper** [comment]
@joeey1984ad From the dmsetup table and status, the dmsetup create's finished.

**Comment by akiradeveloper** [comment]
@joeey1984ad Please let me clarify

* reboot time is proportional to the size of caching device
* drop_caches time is proportional to the write data amount.

**Comment by joeey1984ad** [comment]
whichever, they both never finish, they both hang.

**Comment by joeey1984ad** [comment]
@akiradeveloper 

"dmsetup create's finished" that is true because. I reformatted everything and created a new device. If I run the same command during  reboot time, blank show up.

**Comment by akiradeveloper** [comment]
@joeey1984ad Believe me, writeback and reboot will definitely finish. There are plenty of tests in my testsuite https://github.com/akiradeveloper/writeboost-test-suite.

There are two possibilities:

1. You're doing wrong. It's not clear that your operations is flowless.
2. You failed the module build in your system.

**Comment by akiradeveloper** [comment]
@joeey1984ad 

This is the last time I say this:

"If I run the same command during reboot time, blank show up."

Please show me the sysstat during the second dmsetup create

**Comment by joeey1984ad** [comment]
I am sure. I believe you. But what the heck is wrong!!!?

**Comment by joeey1984ad** [comment]
Ok here is the sysstat after rebooting and second dmsetup create.

![5](https://cloud.githubusercontent.com/assets/12181529/17728098/53445910-6412-11e6-86bd-2c8bf2d26e6c.jpg)

**Comment by joeey1984ad** [comment]
"If I run the same command during reboot time, blank show up."

by that I meant  "dmsetup table" and "dmsetup status mylv"

**Comment by akiradeveloper** [comment]
@joeey1984ad the sysstat is ok. The caching device is read in 38MB/sec. Because your caching device is 470GB. It's going to be approximately 12000seconds. which is about 3hours.

**Comment by akiradeveloper** [comment]
@joeey1984ad What is the reading dev8-32 and writing to dev8-48?

**Comment by joeey1984ad** [comment]
dev8-32 is /dev/sdc HDD
dev8-48 is /dev/sdd HDD 

mdadm -Cv /dev/md0 -l1 -n2 /dev/sdc /dev/sdd

therefore /dev/md0 which is RAID1

Ok, let say 3 hours acceptable for 470gb for reboot second dmsetup create. 
What about droping cache  which is proportional to the write data amount. I only have 6mb. still the drop never finishes.

**Comment by akiradeveloper** [comment]
@joeey1984ad Please show me the `dmsetup status` and sysstat while your dropping caches.

**Comment by joeey1984ad** [comment]
1. dmsetup status mylv    
0 3906766976 writeboost 1225634 111085757 874691 9651 9650 2376 914979 0 159 0 0 1 445 0 0 0 1213245 0 0 0 172 0 0 57 10 writeback_threshold 70 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

2. 
![7](https://cloud.githubusercontent.com/assets/12181529/17728796/e42dd8ae-6415-11e6-8068-94be5443d7a1.jpg)

**Comment by akiradeveloper** [comment]
@joeey1984ad 

You are doing wrong.

The status says there are 914979 dirty blocks. which may be 3GB or so.

To see how fast the writeback finish with 6MB write data, you should clean up the caching device in prior to dmsetup create by zeroing the first sector of the caching device.

The sysstat is benign but your operation was wrong. It's still writing back the dirty data.

**Comment by joeey1984ad** [comment]
hmm. I used "mk2fs.ext4 /dev/md2" before   "dd if=/dev/zero of=/dev/md2 oflag=direct bs=4096 count=1".

**Comment by akiradeveloper** [comment]
> I used "mk2fs.ext4 /dev/md2"

Why did you do this? is it mk2fs.ext4 /dev/mapper/mylv?

**Comment by joeey1984ad** [comment]
I use "mk2fs.ext4 /dev/mapper/mylv" right after dmsetup create correct?

**Comment by akiradeveloper** [comment]
Yes

**Comment by joeey1984ad** [comment]
this is exactly what I did;

1. mkfs.ext4 /dev/md2    

2. dd if=/dev/zero of=/dev/md2 oflag=direct bs=512 count=1

3. dmsetup create mylv --table "0 blockdev --getsize /dev/md0 writeboost /dev/md0 /dev/md2"

4. mkfs.ext4 /dev/mapper/mylv

5. mount /dev/mapper/mylv /home

6. changed "writeback_threshold=70'

7. created around 6mb  DATA on /home

8. dmsetup message mylv 0 drop_caches

**Comment by joeey1984ad** [comment]
1.  dmsetup status
mylv: 0 3906766976 writeboost 1757999 111085757 874691 13843 13842 448 1680144 0 159 0 0 1 446 0 0 0 1735997 0 0 0 259 0 0 93 10 writeback_threshold 0 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

2.  
![7](https://cloud.githubusercontent.com/assets/12181529/17729233/04e18d46-6418-11e6-9d57-91b6e19c2241.jpg)

**Comment by akiradeveloper** [comment]
@joeey1984ad it's ok. 1 is needless though. I think you forgot 2

**Comment by akiradeveloper** [comment]
Sorry the caching device is still too dirty. I bet you again made a mistake.

**Comment by joeey1984ad** [comment]
:) ok I will redo again. wait

**Comment by joeey1984ad** [comment]
1. dmsetup status

mylv: 0 3906766976 writeboost 341202 111085757 874691 2687 2686 1504 147638 0 159 0 0 1 444 0 0 0 335661 0 0 0 59 0 0 25 10 writeback_threshold 70 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

2. sysstat

![8](https://cloud.githubusercontent.com/assets/12181529/17729516/7167c4a2-6419-11e6-9eb3-320e3007b166.jpg)

**Comment by akiradeveloper** [comment]
@joeey1984ad 

> 2687 2686 1504 147638

147638 dirty blocks. This is 600MB if all dirty blocks are 4KB

OK. please redo and give me `dmsetup status` write after `dmsetup create` and `mkfs`.

**Comment by akiradeveloper** [comment]
but I think drop_caches is going to be end

**Comment by joeey1984ad** [comment]
no I am still waiting. drop cache is still waiting.

**Comment by akiradeveloper** [comment]
Please watch the number of dirty cache blocks in the status. When it hits zero is when drop_caches ends

**Comment by joeey1984ad** [comment]
Let me make sure, you want dmsetup status after dmsetup create and mkfs. 
1. Should I upload the 6mb file?
2. should I use the drop command?

**Comment by akiradeveloper** [comment]
@joeey1984ad Yes.

1. dd if=/dev/zero of=/dev/md2 oflag=direct bs=512 count=1
2. dmsetup create mylv --table "0 blockdev --getsize /dev/md0 writeboost /dev/md0 /dev/md2"
3. dmsetup status mylv
4. mkfs.ext4 /dev/mapper/mylv
5. dmsetup status mylv
6. mount /dev/mapper/mylv /home
7. changed "writeback_threshold=70'
8. created around 6mb  DATA on /home
9. dmsetup message mylv 0 drop_caches

**Comment by joeey1984ad** [comment]
3. dmsetup status mylv (dmsetup create mylv)
0 3906766976 writeboost 0 111085757 874691 1 0 0 0 0 114 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10 writeback_threshold 0 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

5. dmsetup status mylv (mkfs.ext4 /dev/mapper/mylv)
0 3906766976 writeboost 39624 111085757 874691 313 312 0 39214 0 148 0 0 0 103 0 0 0 39214 0 0 0 1 0 0 2 10 writeback_threshold 0 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

9 .dmsetup status mylv (after  drop_caches)
0 3906766976 writeboost 249643 111085757 874691 1966 1965 1937 3644 0 159 0 0 1 446 0 0 0 243517 0 0 0 73 0 0 29 10 writeback_threshold 70 nr_cur_batched_writeback 8 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

**Comment by joeey1984ad** [comment]
It seemed to have worked now!! It did drop.

**Comment by joeey1984ad** [comment]
@akiradeveloper I added more data and I am watching the dirty cache going down. In regards to the 6mb file the drop actually finished this time.

**Comment by akiradeveloper** [comment]
@joeey1984ad congrats. So writeback certainly works.

**Comment by joeey1984ad** [comment]
yes it works, something that is puzzling still you mentioned earlier. 

Withthe  writeback_threshold 70,
"Then writeboost writebacks data from caching device to the backing device at the same time you write some data to the writeboost'd device."

then if that is so, what is the need of dropping cache? and what happens if 
writeback_threshold is set to 0 ?

**Comment by akiradeveloper** [comment]
> what is the need of dropping cache?

it is a synchronous call from a userland to wait for forcibly dropping all dirty caches. it set force_drop flag to urge writeback.

```c
	if (!strcasecmp(argv[0], "drop_caches")) {
		int r = 0;
		wb->force_drop = true;
		r = wait_event_interruptible(wb->wait_drop_caches,
			     !atomic64_read(&wb->nr_dirty_caches));
		wb->force_drop = false;
		return r;
	}
```

> what happens if writeback_threshold is set to 0 ?

Writeboost provides autonomous writeback. Which means writeboost surveils the load of backing store and writes back dirty blocks when it's low. Setting 0 to the value means disabling this feature.

**Comment by joeey1984ad** [comment]
@akiradeveloper  this caching device has great potential both in regards to safety and performance. The only drawback I see here is rebooting time. I really am motivated to use this, I will keep exploring the features. Hopefully you will find a way around the booting time issue. Good luck.
