### ISSUE TITLE
write to backdevice not batched?

### ISSUE THREAD

**Issue by bash99** [akiradeveloper/dm-writeboost#153]
Hi, I've try test dm-writeboost and got quick slow down after some fio test. 

### version   
commit 0a8b851560f7637799b652f8cd8f48caac0102df,
OS, centos 7, kernel 3.10.0-327.el7.x86_64

### hardware   
sda is a HDD (500g) and sdb is ssd (240g samsung sm843t)。

### hardware and partition   
    parted --align optimal /dev/sda mkpart primary 10% 50%
    parted --align optimal /dev/sdb mkpart primary 0% 10%

so we have a   
/dev/sda2 190G
/dev/sdb1 22G

### dm-writeboost setup  
    dd if=/dev/zero of=/dev/sdb1 count=1
    dmsetup create wbdev --table "0 `blockdev --getsize /dev/sda2` writeboost /dev/sda2 /dev/sdb1"
    dmsetup message wbdev 2 nr_max_batched_writeback 32
    dmsetup message wbdev 2 writeback_threshold 70

### fio test (I've limit write speed for clear show)  
    fio --name=randwrite --filename=/dev/mapper/wbdev --direct=1 --sync=0 --ioengine=libaio --iodepth=16 --rw=randwrite --bs=16k --size=512M --numjobs=16 --runtime=240 --rate=1M --group_reporting

in the same time,   
    ```iostat -x 5```
reports:  

>avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.16    0.00    2.16    9.20    0.00   87.48

>Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
>sda               0.00   594.00    1.20  209.80    10.40  3376.80    32.11   320.21 1632.62   26.83 1641.81   3.84  81.12
>sdb               0.00     0.00    6.40   32.20  3251.20 16486.40  1022.67     0.04    1.15    1.56    1.07   1.13   4.38
>dm-0              0.00     0.00    0.00 4096.00     0.00 16384.00     8.00     0.03    0.01    0.00    0.01   0.00   1.20

>avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.60    0.00    1.26   10.37    0.00   87.77

>Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
>sda               0.00   592.60    0.00  215.20     0.00  3469.60    32.25   374.58 1633.26    0.00 1633.26   4.27  91.92
>sdb               0.00     0.00    6.40   32.20  3251.20 16486.40  1022.67     0.04    1.13    1.53    1.05   1.11   4.30
>dm-0              0.00     0.00    0.00 4096.00     0.00 16384.00     8.00     0.02    0.01    0.00    0.01   0.00   1.08

so sda show write size is 32 * 512byte(sectors), 16K.
and it need a very long time for all dirty cache write to sda?

I'm new to dm-writeboost, so anything is wrong on my steps?

**Comment by akiradeveloper** [comment]
@bash99 

```
dd if=/dev/zero of=/dev/sdb1 count=1
dmsetup create wbdev --table "0 `blockdev --getsize /dev/sda2` writeboost /dev/sda2 /dev/sdb1"
dmsetup message wbdev 2 nr_max_batched_writeback 32
dmsetup message wbdev 2 writeback_threshold 70
```

Please see the status. It's wrong.

"dmsetup message wbdev 2 nr_max_batched_writeback 32"

should be

"dmsetup message wbdev 0 nr_max_batched_writeback 32"

0 instead of 2 when you send message.

**Comment by bash99** [comment]
@akiradeveloper 
I've got same result after run
```
dmsetup message wbdev 2 nr_max_batched_writeback 32
dmsetup message wbdev 2 writeback_threshold 70
```

output of status
```dmsetup status wbdev```

> 0 383526936 writeboost 3447987 5814568 45784 27150 27149 26660 49293 1 1111 0 0 1 981 0 1 22959 2098663 0 0 517 1303622 23476 140 95 10 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 0

**Comment by akiradeveloper** [comment]
@bash99 

> dmsetup message wbdev 2 nr_max_batched_writeback 32
dmsetup message wbdev 2 writeback_threshold 70

What is this? please use 0

**Comment by akiradeveloper** [comment]
And what is the problem?

**Comment by akiradeveloper** [comment]
Usually, if you are describing a issue. If should be started by "what you expected". What are you hoping for the batched writeback?

**Comment by bash99** [comment]
@akiradeveloper 
Perhaps I've some misunderstand of how dm-writeboost works. 
from dm-writeboost-internal document, 
>Writeback daemon fetches multiple segments (tuned by nr_max_batched_writeback)
>And then sorts all the cache blocks in the segments by the destination address, using rbtree. This can make use of sequential write performance of backing rotational disk.

I've thought "Writeback daemon" will write to HDD in big block size, so the writeback speed will near sequential write performance.
But before set writeback_threshold the 0 (ie. disable writeback)，iostat show "Writeback daemon" write to HDD use the same size of fio random write block size.

And I'm wonder if disable writeback, what happens when cache device is full of dirty block?

**Comment by akiradeveloper** [comment]
> I've thought "Writeback daemon" will write to HDD in big block size, so the writeback speed will near sequential write performance.

No it's just sorting like I/O scheduler. But far better than I/O scheduler.
If you find a method to alwasy writeback in a big size, you can conquerer the world.

> avgrq-sz is 32, so write-size is 16K.

Yes. this is because you randomwrite in 16KB bs.

Now your understanding is corrected.

> And I'm wonder if disable writeback, what happens when cache device is full of dirty block?

Writeboost notices there is no empty segment to write and then it starts writeback to acquire a new segment. The word "disable" means it doesn't writeback in normal situation but does in urgent situation.

But in production use, there is no reason to disable writeback.

**Comment by bash99** [comment]
@akiradeveloper ohh，now I've full understand, sorry for put up this issue and waste your time.
maybe you can add a FAQ entry for dm-writeboose use case. what I can sum up is, hot dataset is small than SSD cache, and long-time write iops is below HDD (so writeback can catch up and clear dirty blocks). It's sound just like any cache, how fool am I!

**Comment by akiradeveloper** [comment]
@bash99 I am writing FAQ page in wiki. https://github.com/akiradeveloper/dm-writeboost/wiki/Frequent-Q&A

As I am getting feedback from users, I can put more contents there.

**Comment by akiradeveloper** [comment]
@bash99 May I close this issue?

**Comment by bash99** [comment]
@akiradeveloper sure you are free to close this.
