### ISSUE TITLE
Degradation: DM_IO_BIO not found in 3.10 kernel

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#158]
In commit (https://github.com/akiradeveloper/dm-writeboost/commit/ee815f26ec815e94dc437712d09cbb7f36390632), we started to use DM_IO_BIO to read from backing store when it's a staging read.

But this caused a degradation. DM_IO_BIO is only found since 3.14

The patch changed DM_IO_BVEC to DM_IO_BIO is https://www.redhat.com/archives/dm-devel/2013-March/msg00114.html

There are two options we can take.

The one is of course, fix this. It seems to be easily fixable.

And the other is discarding the supports for pre-3.14. The kernel 3.14 had drastic change in bio structure and we have several macros to absorb the change. Maintaining these macros are pretty burdening to me.

If there are CentOS 7 users trying writeboost I will definitely take the first one but otherwise I want to do the second. I want to request for comments.

**Comment by akiradeveloper** [comment]
I should not omit testing with 3.10 kernel before release.

**Comment by bash99** [comment]
We try writeboost with CentOS 7. just one percent

**Comment by akiradeveloper** [comment]
@bash99  sorry for the inconvenience. I will fix this and release the new version soon
