### ISSUE TITLE
"blockdev --getsize" is deprecated

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#162]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838293
dm-writeboost documentation suggests to use deprecated `blockdev --getsize`: 
[dm-writeboost-readme.txt#L72](../blob/master/doc/dm-writeboost-readme.txt#L72)

**Comment by akiradeveloper** [comment]
@onlyjob OK. I will fix this in 2.2.7.
