### ISSUE TITLE
Trouble locating dmsetup

### ISSUE THREAD

**Issue by thalatta** [akiradeveloper/dm-writeboost#187]
I'm currently trying to use dm-writeboost and I am having some trouble locating the command for dmsetup.

First, I zero the first block on the ssd: _sudo dd if=/dev/zero of=/dev/sdc count=1_.

Next, I use command _sudo dmsetup create mylv --table "0 \`blockdev --getsize /dev/sdb\` writeboost /dev/sdb /dev/sdc"_.

Terminal replies _sudo: dmsetup: command not found_.

I checked the source and there is nothing that looks like a command line tool dmsetup. This seems very odd, and I'm having some trouble understanding if I'm missing something.

I checked dm-writeboost-tools, and it doesn't look like where dmsetup is located. dmsetup I think should be here in the dm-writeboost source code. But I cannot find it and my computer cannot find it either.

Sorry, I am a beginner.

**Comment by akiradeveloper** [comment]
I guess you should set PATH to the dmsetup?

**Comment by thalatta** [comment]
Thanks for the reply. I didn't realize dmsetup is packaged with Linux. I'll install the dependencies and then it should work.
