### ISSUE TITLE
Problem using dmsetup and writeboost to create device-mapper file

### ISSUE THREAD

**Issue by allenjhan** [akiradeveloper/dm-writeboost#190]
I am currently using DM-writeboost on a virtual machine. The kernel module installs fine.

Last week, I tried using dmsetup with the command

    sudo dmsetup create mylv --table "0 `blockdev --getsize /dev/sdb` writeboost /dev/sdb /dev/sdc"

and it worked fine.

Today, I tried it again and it failed with the error

    device-mapper: reload ioctl on mylv failed: Input/output error
    Command failed

Of course, I remembered to zero the first sector of the cache device. Has anyone ever seen this error while attempting to call dmsetup with DM-writeboost, and do you know what it means?

**Comment by akiradeveloper** [comment]
@allenjhan No. I think you've made some easy mistakes (e.g. the device doesn't exist)

I recommend you to solve this issue by yourself and you will be able to learn much more about Writeboost and Linux. It should be super easy. The dmesg may help.

**Comment by allenjhan** [comment]
I tried several things, but got it to work in the end. The problem seems to be a bad USB port on my computer. If I don't use it, and use the other ones, things seem to work fine.

I didn't know about dmesg, so thanks.
