### ISSUE TITLE
device-mapper: writeboost: Superblock Header: Magic number invalid

### ISSUE THREAD

**Issue by jvinolas** [akiradeveloper/dm-writeboost#196]
I have this message (device-mapper: writeboost: Superblock Header: Magic number invalid) on dmesg when I start writeboost. Is that a problem? Cache seems to work as expected but we are afraid something bad is going on.

lsblk
> NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda           8:0    0  74,5G  0 disk  
├─sda1        8:1    0  42,8G  0 part  /
├─sda2        8:2    0     1K  0 part  
└─sda5        8:5    0  31,7G  0 part  [SWAP]
sdb           8:16   0   7,3T  0 disk  
└─md0         9:0    0   7,3T  0 raid1 
  └─disks1  253:1    0   7,3T  0 dm    
sdc           8:32   0   7,3T  0 disk  
└─md0         9:0    0   7,3T  0 raid1 
  └─disks1  253:1    0   7,3T  0 dm    
sdd           8:48   0   7,3T  0 disk  
└─md1         9:1    0   7,3T  0 raid1 
  └─disks2  253:0    0   7,3T  0 dm    
sde           8:64   0   7,3T  0 disk  
└─md1         9:1    0   7,3T  0 raid1 
  └─disks2  253:0    0   7,3T  0 dm    
nvme1n1     259:0    0   477G  0 disk  
├─nvme1n1p1 259:2    0   238G  0 part  
├─nvme1n1p2 259:3    0   238G  0 part  
└─nvme1n1p3 259:4    0 961,3M  0 part  
nvme0n1     259:1    0 931,5G  0 disk  
├─nvme0n1p1 259:5    0 465,7G  0 part  
│ └─disks1  253:1    0   7,3T  0 dm    
└─nvme0n1p2 259:6    0 465,8G  0 part  
  └─disks2  253:0    0   7,3T  0 dm  

Server has 32G ram and this is dmsetup status:

> disks2: 0 15627790976 writeboost 0 121159905 954015 1 0 0 0 0 125 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10 writeback_threshold 80 nr_cur_batched_writeback 0 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 127
disks1: 0 15627790976 writeboost 0 121122186 953718 1 0 0 0 0 125 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10 writeback_threshold 80 nr_cur_batched_writeback 0 sync_data_interval 0 update_sb_record_interval 0 read_cache_threshold 127

**Comment by akiradeveloper** [comment]
@jvinolas No problem. I think it was the first time you build the writeboost device. It just formatted the caching device because the magic number in the superblock is not correct. Please read the code for more detail.

**Comment by jvinolas** [comment]
It happens every time we mount the cache, not only at creation.

**Comment by akiradeveloper** [comment]
@jvinolas I think you always zero out the first sector of the caching device. By the way, what do you mean by "mount"? There is no notion of mounting a cache.

**Comment by jvinolas** [comment]
I see. It happens when creating the first time with wbcreate and also when booting again and recreating with writeboost command.
Anyway, if it is not an 'error' it is ok.

**Comment by akiradeveloper** [comment]
@jvinolas I don't know precisely what command line you use to create the writeboost device but my guess is that you always add "--reformat" option to the command.

This option will destroy all the cache data in the caching device and reformat the caching device. Therefore, you should not add the option when booting again or you will lose the data, unless you wrote back all the dirty data.
