### ISSUE TITLE
can not compile with linux-4.19

### ISSUE THREAD

**Issue by meke** [akiradeveloper/dm-writeboost#198]
dm-writeboost-2.2.9がlinux-4.19でコンパイルできなくなりました。

手元でコンパイルした限りは、以下の様な問題が発生しているようです。

1.  dm-writeboost-metadata.c内で呼び出している dm_kcopyd_zero がvoid 宣言されるようになり、戻り値が無くなったため、戻り値を取得している箇所がエラーになった
2.  dm-writeboost.h内の「enum STATFLAG」の中で定義されている「STAT_WRITE」と同名のものが、kernel本体の include/linux/blk_types.h 内で定義されているため、多重定義でエラーになった

**Comment by akiradeveloper** [comment]
Memo: There is ever no need for check the return value of dm_kcopyd_zero https://github.com/torvalds/linux/commit/7209049d40dc37791ce0f3738965296f30e26044#diff-a4e88d4ced3769c9bf64974cf11f7db2
