### ISSUE TITLE
how to use dm-writeboost without caching devices(SSD)

### ISSUE THREAD

**Issue by alochym01** [akiradeveloper/dm-writeboost#203]
i read the documents and dm-writeboost has write_around_mode which mean no caching devices

but there is no tutorial steps for using dm-writeboost without ssd caching device

example: i have 256GB(can have to up 512G) RAM, i config 128G rambuff with 20TB of backing device

how can i do it,

**Comment by akiradeveloper** [comment]
> which mean no caching devices

No, write around does not mean no caching device. The mode only bypasses the caching device in write path but will cache later in read.

**Comment by alochym01** [comment]
ok, i got it
