### ISSUE TITLE
Can dm-writeboost be used with gpt disk type?

### ISSUE THREAD

**Issue by nhocchi007** [akiradeveloper/dm-writeboost#205]
lsblk:
sda               8:0    0   2.6T  0 disk 
└─sda1            8:1    0   2.6T  0 part 
  └─ssddisk-ssd 253:3    0   2.6T  0 lvm  
sdb               8:16   0  98.2T  0 disk 
└─sdb1            8:17   0  98.2T  0 part 
  └─hdddisk-hdd 253:4    0  98.2T  0 lvm 
When i use: 
**"wbcreate wbdev /dev/mapper/hdddisk-hdd /dev/mapper/ssddisk-ssd --reformat --writeback_threshold=70"**
1+0 records in
1+0 records out
512 bytes (512 B) copied, 0.00063609 s, 805 kB/s
device-mapper: reload ioctl on wbdev  failed: Invalid argument
Command failed.
thread 'main' panicked at 'assertion failed: status.success()', src/wbcreate/main.rs:108
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by nhocchi007** [comment]
dmsetup ls:
hdddisk-hdd	(253:4)
centos-home	(253:2)
ssddisk-ssd	(253:3)
centos-swap	(253:1)
centos-root	(253:0)

**Comment by akiradeveloper** [comment]
@nhocchi007 You forgot to install dm-writeboost into your system. To answer your question btw, dm-writeboost can be used with any LVM devices and should have no issue with raw GPT device

**Comment by akiradeveloper** [comment]
@nhocchi007 If you installed dm-writeboost from CentOS package. Please contact with the maintainer.

**Comment by nhocchi007** [comment]
yes i use dm-writeboost-dkms.noarch : dm-writeboost 2.2.10 dkms package rpm from repo

**Comment by nhocchi007** [comment]
I try to remove rpm build from source but still the same problem :(

**Comment by nhocchi007** [comment]
I have try to uninstall the rpm build from source then install but still the same problem, how can i chekc whether it was installed or not? dkms build -m dm-writeboost -v 2.2.10

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j72 KERNELRELEASE=3.10.0-957.21.3.el7.x86_64 all KERNEL_TREE=/lib/modules/3.10.0-957.21.3.el7.x86_64/build...
cleaning build area...

DKMS: build completed.
dkms install -m dm-writeboost -v 2.2.10

dm-writeboost.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.10.0-957.21.3.el7.x86_64/extra/
Adding any weak-modules
/etc/sysconfig/network-scripts/ifcfg-bond0: line 1: DEVICEiid: command not found

depmod...

Backing up initramfs-3.10.0-957.21.3.el7.x86_64.img to /boot/initramfs-3.10.0-957.21.3.el7.x86_64.img.old-dkms
Making new initramfs-3.10.0-957.21.3.el7.x86_64.img
(If next boot fails, revert to initramfs-3.10.0-957.21.3.el7.x86_64.img.old-dkms image)
dracut............

DKMS: install completed.

**Comment by nhocchi007** [comment]
oh it show a different dmesg:
[273848.585260] dm_writeboost: loading out-of-tree module taints kernel.
[273848.585476] dm_writeboost: module verification failed: signature and/or required key missing - tainting kernel
[273848.588064] device-mapper: writeboost: Superblock Header: Magic number invalid
[273848.588325] device-mapper: writeboost: zeroing_full_superblock failed
[273848.588361] device-mapper: writeboost: format_cache_device failed
[273848.588711] device-mapper: table: 253:5: writeboost: resume_cache failed
[273848.588769] device-mapper: ioctl: error adding target to table

**Comment by nhocchi007** [comment]
Oh it is running now after i zero 1st sector of cached disk, will update thank you so much akira

**Comment by nhocchi007** [comment]
In your Makefile i line after ' install: '
It's should be: 
**cp -r src $(DKMS_DIR)/src** 
right ?

**Comment by akiradeveloper** [comment]
No because this line expects the dest dir doesnt exist. But it is sure the second install without uninstall will do nothing. Please always uninstall before install
