### ISSUE TITLE
perfomance test

### ISSUE THREAD

**Issue by pipes80-collab** [akiradeveloper/dm-writeboost#231]
i have implented in dmsetup command the threshold then i have forget at first time. now the result is this, in the pic there is a screenshot then is a test without threshold 
![Schermata del 2021-09-02 12-30-58](https://user-images.githubusercontent.com/56699284/131828830-87ad4ba1-40f1-4ca4-8fe1-39d4e40dbee2.png)

**Comment by akiradeveloper** [comment]
@pipes80-collab Which devices did you use in the tests? nvme0n1 and 1n1 are both NVMe devices?

**Comment by pipes80-collab** [comment]
the device is samsung sm851 nvme and 970 pro

**Comment by akiradeveloper** [comment]
@pipes80-collab 

You ran a benchmark program called kdiskmark. What is the target device of each run? From the screenshot use use /home/filippo/kDiskMark. What is the block device behind the directory?

I think the IO from kdiskmark didn't run through the writeboost device which is /dev/mapper/wbdev.

**Comment by akiradeveloper** [comment]
Sorry, I can't help you any more because you don't understand Linux's storage system. You didn't answer my questions correctly.

**Comment by pipes80-collab** [comment]
👍

**Comment by akiradeveloper** [comment]
@pipes80-collab  If you learn the very basics of Linux system (not kernel), you will be able to answer my questions correctly. Please learn before you ask me a question next time.
