### ISSUE TITLE
Is possible use dm-writeboost being a writeback for one disk ?

### ISSUE THREAD

**Issue by Augusto7743** [akiradeveloper/dm-writeboost#232]
Hello.
I has installed dm-writeboost using Ubuntu repository.
I not understand exactly means "log" write cache in software information. You is saying "log" is simply writeback for data file and file system metadata ?
Well ...
Is possible use dm-writeboost for create a writeback cache in RAM for use with only a one disk ?
I want create 2 writeback cache for 2 partitions (/dev/sda2 and /dev/sda3) in one disk (HDD SATA).
If is possible create the caches above has any option to select a defer time to flush data ?

Unhappily I not see any simple command to create the writeback cache thus I not understand if is possible or need a SSD disk for cache.

Thanks for your reply.

**Comment by akiradeveloper** [comment]
@Augusto7743  Unfortunately, I couldn't understand what you mean.

But for the first question

> I not understand exactly means "log" write cache in software information. You is saying "log" is simply writeback for data file and file system metadata ?

You may have to understand the background. This document may help https://docs.google.com/presentation/d/1mDh5ct3OR-eRxBbci3LQgaTvUFx9WTLw-kkBxNBeTD8/edit?usp=sharing
