### ISSUE TITLE
Creating cache device, device busy. Can cache reside in a partition on same physicall device than running OS?

### ISSUE THREAD

**Issue by yevon** [akiradeveloper/dm-writeboost#233]
I have seen this message:

https://github.com/akiradeveloper/dm-writeboost/issues/106

Is impossible to run dm-writeboost inside a separated partition, but in the same device as the running os?

I'm receiving the same error when creating the caching device.

**Comment by yevon** [comment]
I tried creating a LVM device but it didn't work, it says it is busy.

**Comment by akiradeveloper** [comment]
I couldn't understand what you are trying to do. I recommend people to read README or whatever documents to understand Writeboost before trying to use it.
