### ISSUE TITLE
Does not build against Kernel 5.10

### ISSUE THREAD

**Issue by Jinx138** [akiradeveloper/dm-writeboost#234]
Error! Bad return status for module build on kernel: 5.10.83-1-MANJARO (x86_64)
Consult /var/lib/dkms/dm-writeboost/2.2.10/build/make.log for more information:

DKMS make.log for dm-writeboost-2.2.10 for kernel 5.10.83-1-MANJARO (x86_64)
So 12. Dez 15:30:42 CET 2021
make -C /usr/lib/modules/5.10.83-1-MANJARO/build M=/var/lib/dkms/dm-writeboost/2.2.10/build modules
make[1]: Verzeichnis „/usr/lib/modules/5.10.83-1-MANJARO/build“ wird betreten
  CC [M]  /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-target.o
  CC [M]  /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.o
  CC [M]  /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.o
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c: In Funktion »process_deferred_barriers«:
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:62:27: Fehler: zu viele Argumente für Funktion »blkdev_issue_flush«
   62 |                 int err = blkdev_issue_flush(wb->cache_dev->bdev, GFP_NOIO, NULL);
      |                           ^~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ./include/linux/device-mapper.h:12,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost.h:36,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:20:
./include/linux/blkdev.h:1298:5: Anmerkung: hier deklariert
 1298 | int blkdev_issue_flush(struct block_device *, gfp_t);
      |     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.c: In Funktion »format_all_segment_headers«:
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.c:510:15: Fehler: zu viele Argumente für Funktion »blkdev_issue_flush«
  510 |         err = blkdev_issue_flush(dev->bdev, GFP_KERNEL, NULL);
      |               ^~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ./include/linux/device-mapper.h:12,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost.h:36,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.c:20:
./include/linux/blkdev.h:1298:5: Anmerkung: hier deklariert
 1298 | int blkdev_issue_flush(struct block_device *, gfp_t);
      |     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c: In Funktion »do_writeback_segs«:
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:378:9: Fehler: zu viele Argumente für Funktion »blkdev_issue_flush«
  378 |         blkdev_issue_flush(wb->backing_dev->bdev, GFP_NOIO, NULL);
      |         ^~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ./include/linux/device-mapper.h:12,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost.h:36,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:20:
./include/linux/blkdev.h:1298:5: Anmerkung: hier deklariert
 1298 | int blkdev_issue_flush(struct block_device *, gfp_t);
      |     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.c: In Funktion »infer_last_writeback_id«:
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.c:984:16: Warnung: Parameternamen (ohne Typen) in Funktionsdeklaration
  984 |         struct superblock_record_device uninitialized_var(record);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.c:985:39: Fehler: »record« nicht deklariert (erstmalige Verwendung in dieser Funktion); meinten Sie »record_id«?
  985 |         err = read_superblock_record(&record, wb);
      |                                       ^~~~~~
      |                                       record_id
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.c:985:39: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-target.c: In Funktion »writeboost_postsuspend«:
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-target.c:1840:9: Fehler: zu viele Argumente für Funktion »blkdev_issue_flush«
 1840 |         blkdev_issue_flush(wb->cache_dev->bdev, GFP_NOIO, NULL);
      |         ^~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ./include/linux/device-mapper.h:12,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost.h:36,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-target.c:23:
./include/linux/blkdev.h:1298:5: Anmerkung: hier deklariert
 1298 | int blkdev_issue_flush(struct block_device *, gfp_t);
      |     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c: In Funktion »writeback_modulator_proc«:
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:486:40: Fehler: Implizite Deklaration der Funktion »part_stat_read« [-Werror=implicit-function-declaration]
  486 |                 new = jiffies_to_msecs(part_stat_read(hd, io_ticks));
      |                                        ^~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-metadata.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:486:59: Fehler: »io_ticks« nicht deklariert (erste Verwendung in dieser Funktion)
  486 |                 new = jiffies_to_msecs(part_stat_read(hd, io_ticks));
      |                                                           ^~~~~~~~
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:486:59: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funktion, in der er vorkommt, gemeldet
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c: In Funktion »data_synchronizer_proc«:
/var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:578:17: Fehler: zu viele Argumente für Funktion »blkdev_issue_flush«
  578 |                 blkdev_issue_flush(wb->cache_dev->bdev, GFP_NOIO, NULL);
      |                 ^~~~~~~~~~~~~~~~~~
In Datei, eingebunden von ./include/linux/device-mapper.h:12,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost.h:36,
                 von /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.c:20:
./include/linux/blkdev.h:1298:5: Anmerkung: hier deklariert
 1298 | int blkdev_issue_flush(struct block_device *, gfp_t);
      |     ^~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-target.o] Fehler 1
cc1: Einige Warnungen werden als Fehler behandelt
make[2]: *** [scripts/Makefile.build:280: /var/lib/dkms/dm-writeboost/2.2.10/build/dm-writeboost-daemon.o] Fehler 1
make[1]: *** [Makefile:1822: /var/lib/dkms/dm-writeboost/2.2.10/build] Fehler 2
make[1]: Verzeichnis „/usr/lib/modules/5.10.83-1-MANJARO/build“ wird verlassen
make: *** [Makefile:11: all] Fehler 2

**Comment by akiradeveloper** [comment]
@Jinx138 It is already fixed thanks to https://github.com/akiradeveloper/dm-writeboost/pull/216.

According to the changelog, you should use 2.2.12 or later. Unfortunately, you are using 2.2.10.

**Comment by Jinx138** [comment]
Yes. I used the not up-to-date Arch AUR. Thank you.
