### ISSUE TITLE
module build fails for Linux 6.10

### ISSUE THREAD

**Issue by anbe42** [akiradeveloper/dm-writeboost#256]
```
/var/lib/dkms/dm-writeboost/2.2.17/build/dm-writeboost-target.c: In function 'dm_devsize':
/var/lib/dkms/dm-writeboost/2.2.17/build/dm-writeboost-target.c:119:37: error: 'struct block_device' has no member named 'bd_inode'
  119 |         return i_size_read(dev->bdev->bd_inode) >> 9;
      |                                     ^~
```

The corresponding Linux commit is https://github.com/torvalds/linux/commit/203c1ce0bb063d1620698e39637b64f2d09c1368 "RIP ->bd_inode" in v6.10-rc1.

**Comment by akiradeveloper** [comment]
I guess we need the same fix

https://github.com/torvalds/linux/commit/dc0fdfc855bea671ee503f9c706303367bdda946

**Comment by akiradeveloper** [comment]
I think the function was introduced in 5.11. So if I may give up any supports before 5.11. The fix will be easy.

https://elixir.bootlin.com/linux/v5.11-rc1/A/ident/bdev_nr_sectors
