### ISSUE TITLE
Please clarify version of the license

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#56]
Source files of _dm-writeboost_ refer to unversioned "GPL" license. Please clarify which particular versions of GPL license applies? I presume it is [GPL-2+](https://duckduckgo.com/l/?kh=-1&uddg=https%3A%2F%2Fwww.gnu.org%2Flicenses%2Fgpl-2.0.html), right?
The text of the license contains instructions "How to Apply These Terms to Your New Programs" where it suggests the following text to include into source headers:

~~~~
This file is part of dm-writeboost.
Copyright (C) 2012-2015 Akira Hayakawa <ruby.wktk@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
~~~~

Also please include license and copyright statement to `README.md` to make it clear that other files (such as `doc/*`, `Makefile` etc. where license and copyright are not mentioned in the header) are also under GPL-2+.

Thank you.

**Comment by akiradeveloper** [comment]
Thanks. I should be GPL v2.

Adding LICENSE file atop the project tree is conventional in Github but should I copy the statement overall the project?

**Comment by onlyjob** [comment]
You mean GPL v2 (or any later version)? Or GPL v2 (only)?

Adding `LICENSE` is a good idea as GPL-2 recommends to ship copy of the license with software.

IMHO updating headers would be a very good idea in order to correct ambiguous licensing information and to apply license as it recommends. Also it is an opportunity to disclaim liability.

Thank you.

**Comment by akiradeveloper** [comment]
GPL v2 only. As far as I know, Linux kernel module should be under this license.

OK. I will add license statements into only source files (.c and .h). But not into Makefile or docs because it looks to me going too far.

**Comment by onlyjob** [comment]
Thanks. Actually Linux kernel module can be under GPL-2 _compatible_ license. It is always nice to leave room for potential license upgrade, however unlikely it seems to be. Unless you have a reason to prohibit re-licensing under later versions of the license due to distrust to FSF or something like this. I would use GPL-2+ (including later versions), just like the text of the license suggests by default.

You do not need to add new license headers -- it will be perfectly fine to update existing ones and to add text of the license. Also please include license and copyright statement to _README.md_ so this information is accessible without peeking into source code.

Thank you very much.

**Comment by akiradeveloper** [comment]
https://github.com/akiradeveloper/dm-writeboost/commit/eb0453a70642dcea108ce19227373b9750b4cd24 added license statements to source files and README, and add LICENSE term as other Github projects.

**Comment by onlyjob** [comment]
Perfect. Thank you. :)
