### ISSUE TITLE
zram incompatibility

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#60]
I'm getting the following errors in _syslog_ when I'm trying to use _zram0_ block device as dm-writeboost cache:

~~~~
kernel: [18820.076152] device-mapper: writeboost: read_superblock_header() I/O error(-5), bits(18446744073709551615), dev(252:1), sector(0), rw(0)
kernel: [18820.076157] device-mapper: writeboost: read_superblock_header failed
kernel: [18820.076158] device-mapper: writeboost: audit_cache_device failed
kernel: [18820.076287] device-mapper: table: 253:0: writeboost: resume_cache failed
kernel: [18820.076289] device-mapper: ioctl: error adding target to table
~~~~

`/dev/zram0` device is initialised as follows:

~~~~
modprobe -v zram
echo 1024M > /sys/block/zram0/disksize
~~~~

Is it possible to use dm-writeboost with RAM disk?

**Comment by onlyjob** [comment]
dm-writeboost can use `/dev/loop0` on _tmpfs_ as caching device.
Here is how 256M RAM disk can be initialised:

~~~~
/bin/dd if=/dev/zero of=/tmp/ramloop0 bs=1048576 count=256
/sbin/losetup -v /dev/loop0 /tmp/ramloop0
~~~~

**Comment by akiradeveloper** [comment]
Nice testing.

> dm-writeboost can use /dev/loop0 on tmpfs as caching device.

Yes. I have tested with tmpfs before to emulate super-fast SSD. With the benchmark we could know how efficient the code paths of writeboost is.

> I'm getting the following errors in syslog when I'm trying to use zram0 block device as dm-writeboost cache:

So, I am bit surprised to here this. From the user's point view, tmpfs and zram isn't different is my understanding; they are both just a block device.

This log says that read to super block (sector 0) failed and initialization of writeboost caching failed consequently. I am wondering if you can simply read/write the zram device by dd.

```
kernel: [18820.076152] device-mapper: writeboost: read_superblock_header() I/O error(-5), bits(18446744073709551615), dev(252:1), sector(0), rw(0)
kernel: [18820.076157] device-mapper: writeboost: read_superblock_header failed
kernel: [18820.076158] device-mapper: writeboost: audit_cache_device failed
kernel: [18820.076287] device-mapper: table: 253:0: writeboost: resume_cache failed
kernel: [18820.076289] device-mapper: ioctl: error adding target to table
```

**Comment by onlyjob** [comment]
I was surprised so much that I've opened this bug... I have no problem making swap on `/dev/zram0` which actually works pretty much as normal block device except when I'm trying to use it with dm-writeboost...

**Comment by akiradeveloper** [comment]
I found similar issue but with dm-cache.

http://www.redhat.com/archives/dm-devel/2013-December/msg00114.html

I suppose this problem is relevant to device-mapper itself. Some code in device-mapper isn't suitable for using zram as underlying device for example.

**Comment by onlyjob** [comment]
Thank you for explanation. I forgot to answer your question -- yes I can read/write the zram device by `dd` or `ddrescue`.

**Comment by akiradeveloper** [comment]
I will post question to the dm-devel.

**Comment by onlyjob** [comment]
_dm-writeboost_ works perfectly with __brd__ (`/dev/ramN`) RAM disks hence I suppose it doesn't matter if _zram_ disks can not be used.
