### ISSUE TITLE
Should nr_max_batched_writeback be removed?

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#67]
or should it lower the upper bound?

I am considering setting the default value 16 and the range be 1 to 64. It sorts blocks to writeback in a single thread so setting the value 1000 is crazy for CPU usage and computational time.

Stefan's case is because he set this value to 500. This mistake could be typical because user think the higher value is better without any cost. To reduce the support cost by delivering safer software, I want to remove it or lower the upper bound.

**Comment by disaster123** [comment]
I was mainly confused by the name. max batched makes be believe it is a maximum it CAN use but dm writeboost might choose a lower value automagically when it takes too long to wait for it. Another think i still don't know is if this is IOP, kb, MB, sectors ... So i think rename the variable and may be limit the range might be a good solution.

**Comment by akiradeveloper** [comment]
> Another think i still don't know is if this is IOP, kb, MB, sectors

None of them. It's the number of segments!

> So i think rename the variable and may be limit the range might be a good solution.

What's your idea on new name?

**Comment by disaster123** [comment]
But is it the minimum number of segments wb waits before starting writeback or it is the maximum number it writes back in one "run"? Is there any document telling me how that works? Or should i dig into the code? Currently i don't know how this part of wb works.

**Comment by akiradeveloper** [comment]
> it is the maximum number it writes back in one "run"?

This is correct.

> Or should i dig into the code?

Yes. It first calculates how many segments are written back. The number is bounded by the nr_max_batched_writeback. Then it reads all data from the segments, sort them and write back. I don't think the code is easy to understand.

```c
/*
 * Calculate the number of segments to write back.
 */
static u32 calc_nr_writeback(struct wb_device *wb)
{
	u32 nr_writeback_candidates, nr_max_batch;

	nr_writeback_candidates = atomic64_read(&wb->last_flushed_segment_id) -
				  atomic64_read(&wb->last_writeback_segment_id);
	if (!nr_writeback_candidates)
		return 0;

	nr_max_batch = ACCESS_ONCE(wb->nr_max_batched_writeback);
	if (wb->nr_cur_batched_writeback != nr_max_batch)
		try_alloc_writeback_ios(wb, nr_max_batch);
	return min(nr_writeback_candidates, wb->nr_cur_batched_writeback);
}

static bool should_writeback(struct wb_device *wb)
{
	return ACCESS_ONCE(wb->allow_writeback) ||
	       ACCESS_ONCE(wb->urge_writeback)  ||
	       ACCESS_ONCE(wb->force_drop);
}

static void do_writeback_proc(struct wb_device *wb)
{
	u32 k, nr_writeback;

	if (!should_writeback(wb)) {
		schedule_timeout_interruptible(msecs_to_jiffies(1000));
		return;
	}

	nr_writeback = calc_nr_writeback(wb);
	if (!nr_writeback) {
		schedule_timeout_interruptible(msecs_to_jiffies(1000));
		return;
	}

	/* Store segments into writeback_segs */
	for (k = 0; k < nr_writeback; k++) {
		struct writeback_segment *writeback_seg = *(wb->writeback_segs + k);
		writeback_seg->seg = get_segment_header_by_id(wb,
			atomic64_read(&wb->last_writeback_segment_id) + 1 + k);
	}
	wb->num_writeback_segs = nr_writeback;

	do_writeback_segs(wb);

	wake_up(&wb->writeback_wait_queue);
}

int writeback_daemon_proc(void *data)
{
	struct wb_device *wb = data;
	while (!kthread_should_stop())
		do_writeback_proc(wb);
	return 0;
}
```

**Comment by disaster123** [comment]
This looks simple - what i don't understand is then why setting a large value like 500 has a negative impact from from i read it should "just" have a negative impact on CPU due to larger calculation but nothing else. It should also fasten writeback as it can write more sequential data at once. What's wrong in my assumption?

**Comment by akiradeveloper** [comment]
Your assumption is wrong.

It sorts data in O(N logN) so computational impact will be seen. But sorting ~10k data doesn't usually spend 120sec. So, 500 is too big but the cost is not noticeable compared to the I/O time.

The sorted data isn't complete sequential but actually random. Setting bigger data only means higher chance of getting sequentiality after sorting.

Rather, I think what made it timeout is: The massive writeback to poor HDD lengthens the I/O queue too much so average response time worsen.

As we seen in your diskstats, the response time was too low (do you remember after lowering the value, the throughput drastically improved). So I think this is likely for the reason.

**Comment by disaster123** [comment]
OK. But shouldn't the response time to the process writing to the writeboost device stay the same as it gets an ACK back when the data is on the caching device and not on the backing device?

I'm also seeing better application performance by setting nr_max_batched_writeback=2 and worse with nr_max_batched_writeback=8. So i'm already talking about very small values.

**Comment by akiradeveloper** [comment]
> OK. But shouldn't the response time to the process writing to the writeboost device stay the same as it gets an ACK back when the data is on the caching device and not on the backing device?

About when writeboost acks you should read the code. I want to discuss solely based on the fact.

> I'm also seeing better application performance by setting nr_max_batched_writeback=2 and worse with nr_max_batched_writeback=8. So i'm already talking about very small values.

This is likely because your workload is pretty random. No problem

**Comment by disaster123** [comment]
Sorry didn't want to go offtopic. My feeling is i need a better understanding of nr_max_batched_writeback and it's consequences.

As i currently need a value of 2 or 4 i would still like to see it configurable. So please don't remove. Even though i do not understand why it makes a difference for the writing process.

**Comment by akiradeveloper** [comment]
> So please don't remove. 

Sure.

**Comment by akiradeveloper** [comment]
I restricted the value range from 1..1000 to 1..32 and set default to 8.

**Comment by akiradeveloper** [comment]
I will not remove this tunable. So close
