### ISSUE TITLE
Why is writeback disabled by default?

### ISSUE THREAD

**Issue by disaster123** [akiradeveloper/dm-writeboost#70]
Why does somebody want no writeback by default?

**Comment by akiradeveloper** [comment]
It's not because somebody wanted so but just I thought it to be.

It's design issue - I think the kernel part should be simple as it disables these features by default.

The default writeback_threshold was 70 before but I changed to 0 for this reason.

Btw, writeback is disabled isn't correct. It actually writes back when a new clean segment is required. Iow, writeboost can work with writeback_threshold 0

**Comment by onlyjob** [comment]
I was asking myself the same question. I always initialise dm-writeboost devices with `writeback_threshold=70` as `0` doesn't feel like a good default...

**Comment by akiradeveloper** [comment]
Sorry, I can't accept any proposal to set writeback_threshold 0 as the default value.

I think kernel part should be simple to understand. What default value to choose is up to upper layers. So,

@onlyjob If you think the default value should be 70, your script should do so.

Another reason why I keep default values off is that test codes can clarify its intention by eliminating implicitness. Explicitly describing on what configuration it is testing by the code is important.

**Comment by disaster123** [comment]
Don't get it writeback_threshold defaults value is 0.

@akiradeveloper could you please so kind and give me some examples where somebody wants to have writeback_threshold 0 or 50 or 100? I've set it to 100 as the data should go to the backing device as fast as possible to keep the cache device clean. Thanks.

**Comment by akiradeveloper** [comment]
I learned from a book "Information Storage and Management" by EMC that in theory, keeping the load of storage around 70% is ideal. I thought it's proven by the mathematical based on queuing theory. Please read the book if you are interested.

**Comment by disaster123** [comment]
THanks i can aknowledge that it works better with 70 than 100.
