### ISSUE TITLE
cell->cancelled should be touched with mutex held

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#80]
I think this is a bug.

In process_write, a cell could be cancelled in mutex.

```c
		might_cancel_read_cache_cell(wb, bio);

	ret = prepare_new_write_pos(wb);

	ht_register(wb, res.head, ret, &res.key);

	mutex_unlock(&wb->io_lock);
```

So in injecdt_read_cache, it should also be inside mutex otherwise a scenario that

1. cancel the cell
2. write to the HDD acks
3. but the stale data is staged to SSD
4. read hits on SSD

could happen.

```c
static void inject_read_cache(struct wb_device *wb, struct read_cache_cell *cell)
{
	struct metablock *mb;
	u32 _mb_idx_inseg;
	struct ht_head *head;
	struct segment_header *seg;

	struct lookup_key key = {
		.sector = cell->sector,
	};

	if (ACCESS_ONCE(cell->cancelled))
		return;

	mutex_lock(&wb->io_lock);
```

Stefan's case is quite hard to reproduce (it takes days) so this could be the cause.

1. read the metadata -> store into cell
2. check -> OK
3. write new metadata
4. stale metadata on the cell should be cancelled. but not
5. stale metadata is staged
6. check -> NG

If this is true, his case doesn't reproduce with cells->size = 1 but no retest until now.

**Comment by disaster123** [comment]
2.0.6-rc works fine here

**Comment by akiradeveloper** [comment]
Thanks. What a good news.

So I will release 2.0.6-rc as 2.0.6 soon.
