### ISSUE TITLE
Request for doc update, missing description of wb_copy_throttle

### ISSUE THREAD

**Issue by marcin-github** [akiradeveloper/dm-writeboost#89]
Hi!
I'd like to ask to add to dm-writeboost-readme.txt information about wb_copy_throttle, it's new option mainly described inside issues.

**Comment by akiradeveloper** [comment]
Sorry, I searched the word "wb_copy_throttle" inside Issues but not found. What is that?

**Comment by akiradeveloper** [comment]
I see. This is what you mean. 

```c
DECLARE_DM_KCOPYD_THROTTLE_WITH_MODULE_PARM(wb_copy_throttle,
		"A percentage of time allocated for one-shot writeback");
```

**Comment by marcin-github** [comment]
Exactly, I mean module parameter.

**Comment by akiradeveloper** [comment]
The macro creates a static variable `dm_kcopyd_throttle` that's required by `dm_kcopyd_client_create`. For me, it's uncertain how changing the parameter causes to the behavior but I think it should be ok with the initial value.

**Comment by marcin-github** [comment]
Hmm, ok, I shouldn't touch this knob:)
