### ISSUE TITLE
build rpm package

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#94]

**Comment by kazuhisya** [comment]
Hi,

Is this issue still alive?
I am interested in making rpm spec to distribute in rpm.
Could you tell me the current status?

**Comment by akiradeveloper** [comment]
Hi @kazuhisya,

Of course, it still alive.

Some users are trying to deliver writeboost packages to distributions including Debian, Ubuntu, Arch and Gentoo as far as I know. But still we don't have such a nice person to maintain rpm package and push it to CentOS or other rpm-based distributions.

If you like to distribute rpm package, I appreciate it as well. Some of the users compile writeboost in CentOS and actually run it there so it's technically possible.

But note that there is a known problem with CentOS 7.3 because of broken backports https://github.com/akiradeveloper/dm-writeboost/issues/165 . So I recommend you to first build package against 7.2.

**Comment by kazuhisya** [comment]
@akiradeveloper Thanks for the answer!

I was planning to make a repository using [Fedora copr build system](https://copr.fedorainfracloud.org/). (Copr is like ubuntu's PPA.)
You may also know, I think that pushing kernel-modules to the main repository of Fedora/RHEL/CentOS is an especially tough job... Therefore, It's maybe Corp is a good choice as the first step.

At later, I will try to make a copr repository.

**Comment by kazuhisya** [comment]
Hi @akiradeveloper

I prepared a repository for Fedora and RHEL/CentOS. This repository has 2 versions, `kmod` and `dkms`. User can choose either according to preference.
https://copr.fedorainfracloud.org/coprs/khara/dm-writeboost/

BTW, #165 has temporarily applied the workaround patch already presented. I will follow it once this problem is solved.

**Comment by akiradeveloper** [comment]
@kazuhisya Thanks.

So I will soon release 2.2.7 with the fix for #165.
