### ISSUE TITLE
README: broken URL in Related Works

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#95]
"Related Works" refers to obsolete http://embedded.uos.ac.kr/~ysoh/DM-SRC-IBM.pdf

**Comment by akiradeveloper** [comment]
Thank you for reporting.

it seems that ysoh's webpage is entirely gone.

I think I can replace with this (his personal site) https://ysoh.files.wordpress.com/2009/05/dm-src-ibm.pdf
