### ISSUE TITLE
forcible removal of unresponsive dm-writeboost device

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#97]
When underlying block device disappears (e.g. broken or physically removed HDD) dm-writeboost device stops responding. It would be nice if it were possible to forcibly destroy such unresponsive dm-writeboost device without reboot.

**Comment by akiradeveloper** [comment]
Yes. dm-writeboost stops responding in case of such errors as it doesn't ever send side-effects to the backing devices. I call this "block up"

isn't it possible to remove it?

**Comment by onlyjob** [comment]
It did not respond so I couldn't drop it...

**Comment by akiradeveloper** [comment]
the candidate for 2.1.2, for-dmitry branch includes a fix that removes the "block up". So, I believe this issue was addressed at the same time.

**Comment by akiradeveloper** [comment]
Is this issue relevant to #98? If so, I will close this issue

**Comment by onlyjob** [comment]
Yes, I expect this to be addressed by the fix for #98. Thanks.
