### ISSUE TITLE
improve error handling (do not hang on I/O errors)

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#98]
My computer hanged due to _dm-writeboost_ when underlying HDD developed I/O errors on some unreadable sectors. Kernel logged bunch of `blk_update_request` errors (see below) and _dm-writeboost_ device stopped responding. Mounted _xfs_ file system hanged and all applications accessing it froze. Then the whole system stopped responding after when I run `badblocks` to check _dm-writeboost_ device.

Normally minor I/O errors on some HDD sectors are not making the whole file system un-readable. Moreover most of my HDDs are encrypted with _cryptdisk_ which handles I/O errors on underlying HDDs correctly without deadlocks.

Unfortunately _dm-writeboost_ assume that underlying block device is flawless so minor read errors are catastrophic. Without _dm-writeboost_ it is possible to un-mount file system and check block device with `fsck` or `badblocks` as well as to continue reading unaffected files. However dm-writeboost-ed device hangs with reboot as the only way to recover.

~~~~
Jan 13 12:39:38 deblab kernel: [ 3810.144071] sd 2:0:0:0: [sda] tag#28 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Jan 13 12:39:38 deblab kernel: [ 3810.144076] sd 2:0:0:0: [sda] tag#28 Sense Key : Medium Error [current] [descriptor] 
Jan 13 12:39:38 deblab kernel: [ 3810.144078] sd 2:0:0:0: [sda] tag#28 Add. Sense: Unrecovered read error - auto reallocate failed
Jan 13 12:39:38 deblab kernel: [ 3810.144080] sd 2:0:0:0: [sda] tag#28 CDB: Read(16) 88 00 00 00 00 00 fe 9a 41 08 00 00 00 08 00 00
Jan 13 12:39:38 deblab kernel: [ 3810.144082] blk_update_request: 22 callbacks suppressed
Jan 13 12:39:41 deblab kernel: [ 3812.952052] XFS (dm-5): xfs_log_force: error -5 returned.
Jan 13 12:39:41 deblab kernel: [ 3812.952076] XFS (dm-5): Failing async write on buffer block 0xaee6e6b8. Retrying async write.
Jan 13 12:39:41 deblab kernel: [ 3812.952079] XFS (dm-5): Failing async write on buffer block 0xaee6d0d0. Retrying async write.
Jan 13 12:39:41 deblab kernel: [ 3812.952081] XFS (dm-5): Failing async write on buffer block 0xaed6c208. Retrying async write.
Jan 13 12:39:41 deblab kernel: [ 3812.952084] XFS (dm-5): Failing async write on buffer block 0xaee6caa8. Retrying async write.
Jan 13 12:39:41 deblab kernel: [ 3812.952086] XFS (dm-5): Failing async write on buffer block 0xb2d7c448. Retrying async write.
Jan 13 12:39:41 deblab kernel: [ 3812.952089] XFS (dm-5): Failing async write on buffer block 0xaee65448. Retrying async write.
Jan 13 12:39:41 deblab kernel: [ 3812.952091] XFS (dm-5): Failing async write on buffer block 0xaed6baf8. Retrying async write.
Jan 13 12:39:41 deblab kernel: [ 3813.551927] XFS (dm-5): xfs_imap_to_bp: xfs_trans_read_buf() returned error -5.
Jan 13 12:39:42 deblab kernel: [ 3813.591272] XFS (dm-5): xfs_imap_to_bp: xfs_trans_read_buf() returned error -5.
~~~~

**Comment by onlyjob** [comment]
Needless to say that this bug is a blocker for use of _dm-writeboost_ as without the latter minor read errors do not cause freezes forcing reboot of a machine...

**Comment by akiradeveloper** [comment]
I think we need to categorize errors into what's critical and what's minor.

**Comment by akiradeveloper** [comment]
I know the assumption that dm-writeboost stands upon that the backing devices are flawless. But my current block-up strategy is because I couldn't tell which I/O errors should be critical or not. But in theory, it's the matter of implementation. iow, it can

**Comment by onlyjob** [comment]
Perhaps it will be safer not to make any error worse. I mean when it is ever better to freeze the whole machine or make mount point unusable on few unreadable sectors? At the moment it seems to be the worst possible handling of errors...
And it is common when some sectors are unreadable on 3+ TB HDDs so at least that kind of errors should not block I/O... I think cryptsetup layer implements handling of errors quite well...

**Comment by akiradeveloper** [comment]
@onlyjob 

According to my comment

```c
/*
 * Device blockup (Marking the device as dead)
 * -------------------------------------------
 *
 * I/O error on cache device blocks up the whole system.
 * After the system is blocked up, cache device is dead, all I/Os to cache
 * device are ignored as if it becomes /dev/null.
 */
```

dm-writeboost only blocks up in case of erroneous ack from the cache device (SSD), not the backing device (HDD).

Did you really see that error from HDD freezes the writeboost'ed device?

**Comment by akiradeveloper** [comment]
Still, blocking up on error from SSD sounds harmful. My idea now is to fully discard the blocking up.

I trust the errors from devices because they are the result of their all-out efforts (e.g. they may have retried many times but eventually gave up and returns error to the client).

But on the other hand, I distrust the device after error because the error might be due to their internal state is broken. In such case, I can't trust their OK or NO anymore because they are insane. The worst case is that they acks OK even though they are returning wrong data. (*)

In conclusion, only I can trust is their first erroneous ack. That's why I block up the whole device immediately after the first error - meaning that even read requests are all rejected. (to protect clients from read wrong data that's read from cache device)

*If* we can relax (*), we can discard blocking up and just returns data from underlying devices as they are (it's how I deal with the backing device now). By doing so, writeboost'ed device can avoid becoming dead due to the once-in-a-million error from the cache device. Such error is possible in case the request is too much to the device.

**Comment by akiradeveloper** [comment]
FYI, all requests are rejected when it blocks up is implemented as follows

process_write:
```c
	if (is_live(wb))
		bio_endio_compat(bio, 0);
	else
		bio_endio_compat(bio, -EIO);
```

process_read:
```c
	if (!is_live(wb))
		bio_io_error(bio);
```

**Comment by onlyjob** [comment]
> Did you really see that error from HDD freezes the writeboost'ed device?

Positive. Problem manifested on system where caching device is RAM disk. I specifically reproduced the problem with `badblocks` on writeboost'ed device. Now I removed dm-writeboost caching and mount HDD directly -- there are few unreadable sectors but otherwise it works just fine.

**Comment by akiradeveloper** [comment]
I guess when write back IO fails your device freezes.

I am thinking of deprecating block up mechanism. That would avoid freeze your system like now but not sure it becomes removable after being frozen.

**Comment by akiradeveloper** [comment]
I am going to fix this issue this weekend

**Comment by onlyjob** [comment]
Thank you. :-)

**Comment by akiradeveloper** [comment]
@onlyjob I've just pushed for-dmitry branch that should fix this issue. Please give it a shot?

**Comment by akiradeveloper** [comment]
This is a code from 2.1.1's `process_read` and was a serious bug. When it blocks up after disk failure, it acks twice on a read. Next release includes fix to this bug.

```c
	if (!is_live(wb))
		bio_io_error(bio);

	return DM_MAPIO_REMAPPED;
```

**Comment by onlyjob** [comment]
Interesting. It looks like I might have experienced this bug.

Sorry but I still had no chance to try "for-dmitry" branch yet. HDD where I encountered error remapped all its bad blocks. On those disks unreadable blocks may persist for a very long time until data is (re-) written. HDD belong to chunk server that isolated error automatically... I need to find another HDD exhibiting similar problem and it takes time...

**Comment by akiradeveloper** [comment]
@onlyjob With the fixes in for-dmitry branch, I believe, the device won't block up after one-time (or minor) failure. So, in theory, it will be ok if the backing devices turns between states that it's always returning success and failure.

Finding a HDD that's exhibiting the same problem is supposed to be hard, so I propose to use dm-flakey to emulate the situation. The DM stack is useful to emulate such device.

or do you think I should ship the fixed version as soon as possible without your ack? I think I want an ack from you.

**Comment by onlyjob** [comment]
Thanks, I should probably try "dm-flakey" some time. But I'm not familiar with it yet so I can't be confident if it behaves like real device.

I've managed to find HDD exhibiting the same problem. I've tested it with `badblocks` through _dm-writeboost_ and I'm happy to report that it did not hang and behaved just like real device, returned errors properly and could be successfully detached.
All good so I vote for releasing.
Thank you very much, Akira. _dm-writeboost_ is so much better with your recent improvements.

:+1:

**Comment by onlyjob** [comment]
I'll be using real file system on top of dm-writeboost'ed HDD with bad sectors so I'll have a chance to test longer and observe if there will be any troubles. Thanks.

**Comment by akiradeveloper** [comment]
Oh, thanks. So I'm going to release soon after doing some refactorings.

**Comment by onlyjob** [comment]
Excellent. Looking forward to deploy new release. :)

**Comment by akiradeveloper** [comment]
v2.1.2 is released. I will close this issue

**Comment by onlyjob** [comment]
Awesome, awesome, awesome! :) Thanks!
